<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lance Brady">
<meta name="dcterms.date" content="2025-02-18">

<title>Blog Post #1: Lineup Protection or Lineup Penalty? – Lance’s Lineups</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Lance’s Lineups</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/lance-brady-979b4a196/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lancebrady15/lances-lineups"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Blog Post #1: Lineup Protection or Lineup Penalty?</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">lineup protection</div>
                <div class="quarto-category">lineups</div>
                <div class="quarto-category">statcast</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Lance Brady </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 18, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="takeaways" class="level2">
<h2 class="anchored" data-anchor-id="takeaways">Takeaways</h2>
<ol type="1">
<li><p>Fixed-effects linear models of xwOBA supports the idea of a lineup penalty, where having a better hitter on deck may lead to worse outcomes for the current batter.</p></li>
<li><p>While the impact of the next batter’s xwOBA remains directionally consistent across models, its reduced magnitude and marginal significance in our model of xwOBA deviations from season-long averages highlight the challenges of predicting performance deviations rather than raw outcomes.</p></li>
<li><p>Some of the league’s best pitchers perform better when a strong hitter is on deck, serving as an indication of mental aptitude or ability to elevate in high-leverage moments that makes them so successful. This suggests that the effects of lineup protection/penalty may not be a universal phenomenon and that individual pitchers may have different responses to it.</p></li>
<li><p>While overall offensive outcomes are negatively impacted by the next batter’s xwOBA, the underlying components of this effect align in part with previous research on lineup protection. The clearest mechanisms appear to be a reduction in walks and suppression of extra-base hits, paired with an increase in weak contact leading to outs, while singles are not significantly affected. These results suggest that the quality of the next batter influences the pitcher’s approach—leading to fewer walks and more aggressive strategies that ultimately reduce the likelihood of high-value offensive outcomes for the current hitter.</p></li>
<li><p>Even when controlling for batter skill, matchup effects, and game state, a higher next_batter_xwOBA is associated with a small but statistically significant decrease in the current batter’s expected batting average (xBA) for that plate appearance. If the next batter’s xwOBA goes up by 0.100, we estimate a ~-0.003 reduction in pa_xBA per plate appearance—over 500 plate appearances, that amounts to about 1.5 fewer expected hits compared to otherwise.</p></li>
<li><p>When we select for certain statistically significant fixed and random effects, we find that the next batter’s xwOBA continue to have a small but significant impact on the current plate appearance’s xwOBA, and this effect is negative. A stronger on-deck hitter results in lower than expected outcomes for that plate appearance.</p></li>
</ol>
</section>
<section id="introduction-to-lineup-protection" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-lineup-protection">Introduction to Lineup Protection</h2>
<p>Batting order optimization is a heavily studied aspect of baseball decision-making, where teams construct lineups to maximize run production. Most studies in this area assume that hitters in the lineup are independent of one another. However, the concept of lineup protection—the idea that a hitter’s performance is influenced by the quality of the hitter after them—remains debated within the sabermetrics community, most often not believed in by it; it has not been supported by previous statistical studies. Although batting order decisions may offer only marginal advantages in expected runs, in an era where every competitive edge counts, even subtle effects like lineup protection deserve closer examination. The theory behind lineup protection is that a hitter with a good hitter behind them will be harder to pitch around because pitchers won’t want to face the guy after him either, particularly with more runners on base. Thus, walks would decrease, and that would mean more fastballs, strikes, and pitches over the plate, essentially increasing the probability for productive hitting, specifically extra-base hits (doubles, triples, and homeruns).</p>
<p>There are two main ways to study lineup protection:</p>
<p><strong>Pitcher-Centric Analysis:</strong> Examining how pitchers alter their approach based on the quality of the next hitter. Previous research using 30 hitter pairs since the advent of Statcast suggested that protected hitters see an average of 0.25% more strikes compared to league average, and 0.07% more pitches down the middle of the zone. This would lead to 6 additional strikes and 2 additional pitches down the middle over a season. This study was extremely limited, however, and did not account for situations without protection, only used 30 pairs of hitters, and only compared the strike percentage a protected hitter received to the league average of that year, not to the strike percentage they had in other non-protected plate appearances. If lineup protection were to exist, teams should avoid wasting lineup protection on free swingers (putting free swingers before “protectors”) so that the protection is not wasted on hitters who would swing at a higher rate anyway (The Paraball Notes, 2024). Quantitatively, the hitter who bats behind you SHOULD impact the pitches you see, because the run expectancy of certain plays occurring (like walks) would change based on who the following batter is (Weinberg, 2013). Evidence of certain pairs often seems to point to the opposite, with a 2012 evaluation of players hitting after Andrew McCutchen, Ryan Braun, and Joey Votto showing no evidence that pitchers were pitching them differently based on the protection they had (Cameron, 2012).</p>
<p>Hall of Famer Miguel Cabrera attributed part of his power struggles early in the 2019 season to a lack of lineup protection, essentially calling out productive-yet-not-spectacular hitter behind him, Niko Goodrum, saying, “In the past… I got a big bat behind me. You see the way guys pitch me? that explains everything.” His manager responded by saying his statement was “crazy.” Data revealed that he wasn’t getting particularly fewer fastballs, strikes, or good pitches to hit in general, and that in his particular case, there wasn’t evidence for lineup protection (Stavenhagen, 2019).</p>
<p><strong>Hitter Outcome Analysis:</strong> Investigating whether the quality of the next hitter influences the current hitter’s performance. Pre-Pitch F/X research found that pitchers who know that a good hitter is up next will “pitch around” the current hitter, resulting in significantly more walks, and moderately more strikeouts. However, it found that when it comes to putting the ball in play, there was no significant impact (Tango, 2006). Much of the sabermetric community says that lineup protection is a myth, and that a player’s production is almost solely determined by their own skills; luck and random variation also play a small role (Ambrosino, 2011). A 2008 study found that with a small magnitude, the quality of the on-deck hitter negatively impacts the preceding hitter (Bradbury, 2008).</p>
<p>However, a study in 2011 using Retrosheet play-by-play data from 2002-2009 MLB seasons found that power numbers did have significant differences in situations of potential lineup protection. This study argues that previous evidence of lineup protection was not uncovered because endogeneity bias introduced by managers selectively choosing their lineups. For a player’s own performance, they likely are hitting better than their own season averages when they are near the top of the lineup (they have more protection) because they are already doing well at that time for a number of reasons. A good hitter who, for whatever reason, is hitting poorly will be put at the bottom of the lineup (and have less protection), but likely hit well at that spot, and thus, we would observe better hitting with less protection. Thus, protection and performance numbers become tangled in unobservable ways. While these endogeneity issues are a concern, they seem to work in both directions, and with a robust enough dataset, we should be able to see the effects of lineup protection, if it is a real phenomenon.</p>
<p>Using injuries to a batter’s “protector” as a quasi-random natural experiment, this study finds that batters who have stronger protection (i.e., a higher OPS hitter behind them) produce significantly more power. Specifically, a 100-point increase in the protector’s OPS correlates with a 9.7% rise in extra-base hits, and the effect is especially pronounced for third hitters (a 26% increase). The results also suggest that when left unprotected, batters draw more walks—particularly intentional walks, as previous literature has supported (Phillips, 2011). It also found that hits in general remained unchanged with protection or not, suggesting that batters are not simply putting the ball into play fewer times, but having less powerful, and thus, productive, contact. However, this study simply made claims about the distribution of outcomes and not about overall offensive production. Protected hitters got fewer walks and more extra-base hits, which act in opposing manners. Our study will use Expected Weighted On-Base Average, an offensive statistic that correlates directly with a player’s overall contribution to run production from the plate, to tackle this gap in research.</p>
<p>We will also use a large sample size of over 3 million plate appearances from 2015-2024 to ensure that our results are robust.</p>
<p>Most other previous literature of hitter outcome analysis has been rather anecdotal, focusing on specific players and how they fare with protection. Using over 3000 Plate Appearances from Pete Alonso’s career before his 2024 season, we can see higher slugging percentages with better hitters behind him, along with being 11% more likely to homer. With worse protection, he is more likely to walk, although his strikeout rates go against previous research and actually decrease with poor hitters behind him (Britton, 2024). Other research takes specific teams and analyzes whether the topic of lineup protection even applies and whether it serves a purpose in that roster’s decision-making. When the Diamondbacks acquired Mark Trumbo in 2014, writers brought up the fact that even though Trumbo’s power threat could serve to protect Paul Goldschmidt, Trumbo may not even be much better than other Diamondbacks hitters who could replace him in terms of offensive threat in general (Wiser, 2014). In 2015, Billy Hamilton pointed to a different sort of offensive advantage owing to the hitter behind him–knowing Joey Votto was hitting after him, an incredibly selective hitter often with long counts, allowed Hamilton to be patient and wait for the right pitch to steal on. In this situation, with a small sample size, the threat of Votto was preventing opposing pitchers from throwing fastballs with Hamilton on base, allowing Hamilton to get better base-stealing opportunities (Petriello, 2015).</p>
<p>It is worth noting that many within baseball discuss lineup protection with certainty. Alonso had pushed for J.D. Martinez to join and hit behind him for the Mets in 2024, hoping it would help his offensive statistics. Interviews with several within the game in 2015 resulted in a plethora of answers, from Joe Girardi saying lineup protection was most significant in lefty-righty matchups, Madison Bumgarner saying he doesn’t pay attention to the on-deck circle, Tim Hudson saying that it’s “foolish if you don’t look at the next hitter,” and multiple other pitchers saying it is a factor in their decision-making, especially later in the game (Laurila, 2016).</p>
<p>It is also worth noting that these anecdotal examinations are subject to sample size constraints and extremely limited in their ability to observe lineup protection on a large scale in Major League Baseball. This article aims to tackle that problem.</p>
</section>
<section id="aim" class="level2">
<h2 class="anchored" data-anchor-id="aim">Aim</h2>
<p>This article aims to provide further insights into lineup protection using pitch-by-pitch data Statcast data from the 2015 to 2024 Major League Baseball seasons, focusing on analyzing hitter outcomes. While literature is mixed and often negative on the existence of lineup protection, it often uses anecdotal evidence, and a more thorough investigation is necessary, especially one using the more advanced expected statistics we now have available.</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>We would like our independent variables to be the following:</p>
<ul>
<li><p>Current pitcher fixed effects</p></li>
<li><p>Current hitter fixed effects</p></li>
<li><p>Current hitter’s handedness</p></li>
<li><p>Next hitter’s handedness</p></li>
<li><p>Next hitter’s underlying quality (e.g.&nbsp;xwOBA)</p></li>
<li><p>Base-out state</p></li>
<li><p>Inning</p></li>
<li><p>Run differential</p></li>
</ul>
<p>Previous studies have looked at protection as a binary independent variable, but that is a narrow view on lineup protection. Lineup protection must be considered as a continuous variable because some players will protect more than others.</p>
<p>Our outcome variable for our first model will be that plate appearance’s xwOBA, which will essentially give us the quality of that plate appearance based on the independent variables. We would then like to see what factor the quality of the next batter has in the outcome.</p>
<p>We will use a mixed-effects linear model to account for the random effects of pitchers and batters. Our models are described in detail below.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>For full methods and model outputs <a href="../../appendix/blog1-appendix.html">view the full appendix here</a>.</p>
<p>It is worth noting that originally Random Effects were included for both the pitcher and batter, but a fixed effects model proved more fruitful for getting estimates of the effects of the next batter’s xwOBA.</p>
</section>
<section id="model-1-linear-models-of-xwoba-of-plate-appearances" class="level2">
<h2 class="anchored" data-anchor-id="model-1-linear-models-of-xwoba-of-plate-appearances">Model #1: Linear Models of xwOBA of Plate Appearances</h2>
<section id="i.-overall-offensive-value-woba-and-xwoba" class="level3">
<h3 class="anchored" data-anchor-id="i.-overall-offensive-value-woba-and-xwoba">I. Overall Offensive Value: wOBA and xWOBA</h3>
<p><strong>Model 1</strong>: Fixed Effects Linear Model of xwOBA of Plate Appearances</p>
<p>Our first model will be a mixed-effects linear model of plate appearances, where we will use the xwOBA of the current plate appearance as our outcome variable. We will use the season-long xwOBA of the current and next batters as our main independent fixed effect, and we will also include the batter’s handedness matchup, the next batter’s handedness matchup, the baserunner state, outs when up, run differential, and game year as fixed effects. We will also include random effects for pitcher. Note that the next batter’s handedness matchup is the handedness of the next batter with the handedness of the current pitcher, and thus does not account for potential anticipated calls to the bullpen (when a pitcher knows they are coming out after the current batter) or pinch-hitting situations. Also note that there is no random effect for <code>Batter</code>, as singularities arise when we include it, due to batters being accounted for in <code>batter_xwOBA</code>.</p>
<p>The model is as follows:</p>
<p><span class="math display">\[
\begin{aligned}
\text{xwOBA}^{\text{PA}}_{ij} &amp;= \beta_0 + \beta_1 \cdot \text{xwOBA}^{\text{Next Batter}}_{ij} + \beta_2 \cdot \text{Matchup}^{\text{Current}}_{ij} + \beta_3 \cdot \text{Matchup}^{\text{Next}}_{ij} \\
&amp;\quad + \sum_{k} \beta_{4k} \cdot \text{BaserunnerState}_{ijk} + \beta_5 \cdot \text{Outs}_{ij} + \beta_6 \cdot \text{RunDiff}_{ij} \\
&amp;\quad + \alpha_{\text{BatterYear}_i} + \alpha_{\text{PitcherYear}_j} + \varepsilon_{ij}
\end{aligned}
\]</span></p>
<p>where the following are the variables:</p>
<ul>
<li><span class="math inline">\(\text{xwOBA}^{\text{PA}}_{ij}\)</span>: Expected weighted on-base average for plate appearance <span class="math inline">\(i\)</span> against pitcher <span class="math inline">\(j\)</span>.</li>
</ul>
<p>Key Predictors:</p>
<ul>
<li><p><span class="math inline">\(\text{xwOBA}^{\text{Next Batter}}_{ij}\)</span>: Expected wOBA of the batter who follows in the lineup.</p></li>
<li><p><span class="math inline">\(\text{Matchup}^{\text{Current}}_{ij}\)</span>: A binary indicator for the handedness advantage of the current batter (e.g., lefty vs.&nbsp;righty).</p></li>
<li><p><span class="math inline">\(\text{Matchup}^{\text{Next}}_{ij}\)</span>: A binary indicator for the handedness advantage of the next batter.</p></li>
</ul>
<p>Control Variables:</p>
<ul>
<li><p><span class="math inline">\(\text{Baserunners}_{ij}\)</span>: A set of indicators for the base-out state (e.g., runner on 1B, 2B-3B, etc.).</p></li>
<li><p><span class="math inline">\(\text{Outs}_{ij}\)</span>: Number of outs when the plate appearance begins.</p></li>
<li><p><span class="math inline">\(\text{RunDiff}_{ij}\)</span>: Run differential from the batting team’s perspective before the plate appearance.</p></li>
</ul>
<p>Fixed Effects: - <span class="math inline">\(\alpha_{\text{PitcherYear}_j}\)</span>: Pitcher-year fixed effects to account for time-varying differences in pitcher quality. - <span class="math inline">\(\alpha_{\text{BatterYear}_i}\)</span>: Batter-year fixed effects to account for time-varying differences in batter quality. - <span class="math inline">\(\varepsilon_{ij}\)</span>: Residual term capturing unexplained variation in plate appearance xwOBA.</p>
<p>In this model, i indexes individual plate appearances and j indexes the pitcher. This plate appearance’s expected xwOBA baseline is adjusted by a pitcher-year–specific intercept, <span class="math display">\[u_{0, \text{PitcherYear}_j}\]</span>, that varies randomly across pitchers and seasons. Batter and contextual features are treated as fixed effects. While we had originally considered <strong><code>Year</code></strong> as a fixed effect, including a random intercept for each pitcher-year combination offers a more targeted way to account for year-to-year changes. This approach captures how a pitcher’s baseline performance may shift over time, effectively absorbing much of the year-specific variation without relying on broad, league-wide year indicators. A two-way ANOVA test using models with and without <code>Year</code> yielded it not statistically significant. We will use Plate Appearances where the pitcher has faced at least 30 batters, the batter had at least 200 plate appearances (so their overall value was relatively stable), and made sure each batter/next-batter pair had at least 40 plate appearances together to ensure we are accurately accounting for a batter having different results with different batter abilities following them.</p>
<p><strong>Table 1</strong></p>
<table class="texreg caption-top table" data-quarto-postprocess="true">
<caption>Comparison of Mixed Effects Models</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Model 1: FE xwOBA</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Model 2: xwOBA Diff</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Model 3: RE Slope</th>
</tr>
</thead>
<tbody>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Intercept</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0005</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0055)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">1.0181<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0128)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0431<sup>*</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0201</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0307<sup>*</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0177)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0112)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0133)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Current Matchup</td>
<td style="padding-left: 5px; padding-right: 5px">0.0327<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0205<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0194<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0012)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0010)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0010)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Next Matchup</td>
<td style="padding-left: 5px; padding-right: 5px">0.0026<sup>*</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0014</td>
<td style="padding-left: 5px; padding-right: 5px">0.0009</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0010)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0009)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0010)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0005</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0003</td>
<td style="padding-left: 5px; padding-right: 5px">0.0015</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0012)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0012)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0013)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B-2B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0006</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0006</td>
<td style="padding-left: 5px; padding-right: 5px">0.0010</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0018)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0019)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0021)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0028</td>
<td style="padding-left: 5px; padding-right: 5px">0.0028</td>
<td style="padding-left: 5px; padding-right: 5px">0.0027</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0027)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0027)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0031)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">2B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0059<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0059<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0061<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0016)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0016)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0018)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">2B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0008</td>
<td style="padding-left: 5px; padding-right: 5px">0.0006</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0014</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0031)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0031)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0036)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0043</td>
<td style="padding-left: 5px; padding-right: 5px">0.0044</td>
<td style="padding-left: 5px; padding-right: 5px">0.0071<sup>*</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0027)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0026)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0031)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Loaded</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0021</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0024</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0027</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0029)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0031)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0036)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Outs</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0035<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0035<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0043<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0006)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0005)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0006)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Run Diff</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0009<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0009<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0001</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0002)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0002)</td>
<td style="padding-left: 5px; padding-right: 5px">(0.0002)</td>
</tr>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Num. obs.</td>
<td style="padding-left: 5px; padding-right: 5px">779106</td>
<td style="padding-left: 5px; padding-right: 5px">779106</td>
<td style="padding-left: 5px; padding-right: 5px">622199</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: BatterYear</td>
<td style="padding-left: 5px; padding-right: 5px">3578</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: PitcherYear</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
<td style="padding-left: 5px; padding-right: 5px">2876</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0256</td>
<td style="padding-left: 5px; padding-right: 5px">0.0127</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0011</td>
<td style="padding-left: 5px; padding-right: 5px">0.0008</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0142</td>
<td style="padding-left: 5px; padding-right: 5px">0.0057</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0011</td>
<td style="padding-left: 5px; padding-right: 5px">0.0008</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">AIC</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">565947.4543</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">BIC</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">566140.2515</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Log Likelihood</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">-282956.7271</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Var: PitcherYear (Intercept)</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.0004</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Var: PitcherYear × Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.0029</td>
</tr>
<tr class="odd" style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Var: Residual</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.1449</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="4" style="font-size: 0.8em"><sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05</td>
</tr>
</tfoot>

</table>


<p style="font-size: 0.9em; font-style: italic;">
Model 1 predicts plate appearance-level expected wOBA (xwOBA).<br> Model 2 predicts the deviation from each batter’s season-long xwOBA in a given plate appearance.<br> Model 3 predicts plate appearance-level expected wOBA (xwOBA), including a random slope for the Next Batter’s xwOBA by PitcherYear to account for varying sensitivity to protection.
</p>
<p><strong>Reference levels:</strong> <code>baserunner_state</code> = Empty, <code>game_year</code> = 2015. Categorical variables are dummy-coded.</p>
<p>It is verifying that our <code>current_matchup_advantage</code> is positive and statistically significant, with a coefficient of 0.0327, indicating that the batter’s handedness matchup advantage does have a positive impact on the xwOBA of the current plate appearance, which is a known facet of baseball.</p>
<p>When accounting for all of the other variables, we can see that the coefficient of <code>next_batter_xwOBA</code> is negative, at -0.0431, and significant at the <span class="math inline">\(\alpha\)</span> = 0.05 level.</p>
<p>This coefficient means that with a 0.100 increase in the next batter’s xwOBA, we would expect a 0.00431 decrease in the current plate appearance’s xwOBA. This is a small effect, but it is statistically significant and suggests that a reverse lineup protection, or a lineup penalty does exist to some degree when a better hitter is on deck.</p>
<p>We find that a matchup advantage on deck also has a significant impact on the current plate appearance’s xwOBA, with a coefficient of 0.0026, indicating that a matchup advantage for the next batter does have a positive impact on the current plate appearance’s xwOBA. This is more in line with lineup protection, although it is a very small effect.</p>
<p>While we will want to use model selection techniques to check if all of these variables are important, other significant coefficients make sense. The only <code>baserunner_state</code> with a significant coefficient is when a runner is on 2B, with a positive coefficient of 0.0059, indicating that having a runner on 2B increases the xwOBA of the current plate appearance compared to having nobody on base. These are situations of stress on the pitcher, where they often have to focus a lot on the player at second, and with the runner being in scoring position, they will be extra nervous about run-scoring potential. One hypothesis for why this might happen when a runner is on second but not when a runner is on third is that there is rarely a factor of the pitcher paying attention to holding a runner on at third, and instead can just focus on the batter at hand. However, the coefficient for <code>3B</code> is still marginally significant at the <span class="math inline">\(\alpha = 0.1\)</span> level. The <code>Outs</code> variable has a negative and significant coefficient, indicating that having more outs when up decreases the xwOBA of the current plate appearance. The <code>run_diff</code> variable has a negative and significant coefficient, indicating that having a larger run differential decreases the xwOBA of the current plate appearance. This could be that when a team is down, on average, they might put in better pitchers, or batters lose focus when they think they will already win. Overall, this effect is incredibly small.</p>
<p><strong>Takeaway</strong>: Our fixed-effects linear model of xwOBA supports the idea of a lineup penalty, where having a better hitter on deck may lead to worse outcomes for the current batter.</p>
<p><strong>Model 2</strong>: Fixed Effects Model of xwOBA Difference</p>
<p>Model 2 is a mixed-effects linear model of plate appearances, where we will use the xwOBA difference of the current plate appearance from the batter’s season long average as the outcome variable. We will use the xwOBA of the next batter as our main independent variable, and we will also include the batter’s handedness, the next batter’s handedness, the baserunner state, outs when up, run differential, and game year as fixed effects. We will also include random effects for pitcher.</p>
<p>The model is as follows:</p>
<p><span class="math display">\[
\begin{align*}\text{xwOBADiff}^{\text{PA}}_{ij} &amp;= \beta_0 + \beta_1 \cdot \text{xwOBA}^{\text{Next Batter}}_{ij} \\&amp;\quad + \beta_2 \cdot \text{Matchup}^{\text{Current}}_{ij}+ \beta_3 \cdot \text{Matchup}^{\text{Next}}_{ij} \\&amp;\quad + \beta_4 \cdot \text{Baserunners}_{ij}+ \beta_5 \cdot \text{Outs}_{ij} \\&amp;\quad + \beta_6 \cdot \text{RunDiff}_{ij} \\&amp;\quad \alpha_{\text{BatterYear}_i} + \alpha_{\text{PitcherYear}_j} + + \varepsilon_{ij}\end{align*}
\]</span></p>
<p>The variable names are the same as in Model 1. Coefficients in Model 2 closely mirror those of Model 1 in both direction and significance, with one key exception: the coefficient for <code>next_batter_xwOBA</code> decreases in magnitude to -0.0201 and is only marginally significant at the <span class="math inline">\(\alpha = 0.1\)</span> level. This further supports the idea that the next batter’s expected offensive output has a small but nontrivial negative impact on the current plate appearance’s xwOBA. It’s worth noting that Model 2 likely appears noisier because it predicts deviation from a batter’s season-average performance — a quantity with lower variance and, correspondingly, a lower signal-to-noise ratio. This makes the outcome more sensitive to stochastic or unobserved game-level effects.</p>
<p>Aside from this difference, coefficients remain largely stable across Models 1 and 2, suggesting that the underlying relationships are consistent. For interpretability, however, we return to predicting <code>pa_xwOBA</code> in Model 3, as it is more intuitive than modeling deviations from a batter’s season average.</p>
<p><strong>Takeaway:</strong> While the impact of the next batter’s xwOBA remains directionally consistent across models, its reduced magnitude and marginal significance in our model of xwOBA deviations from season-long averages highlight the challenges of predicting performance deviations rather than raw outcomes.</p>
<p><strong>Model 3: Incorporating a Random Slope for the Next Batter’s xwOBA</strong></p>
<p>If we now want to incorporate how different pitchers are affected by the next batter, we can add a slope for the next batter’s xwOBA as a random effect. This will allow us to see how the effect of the next batter’s xwOBA varies by pitcher. We do not expect an equivalent effect with batters, as players describe how the pitcher will act differently based on the abilities of the next batter, not the batter. To make sure there is enough data to get a good estimate of these slopes, we will only include pitchers with at least 100 plate appearances in our dataset for a given year. We will treat the slope and intercept independently, as we do not expect that pitchers who allow higher/lower overall xwOBA also respond differently to lineup protection.</p>
<p>The model is as follows:</p>
<p><span class="math display">\[
\begin{align*}\text{xwOBA}^{\text{PA}}_{ij} &amp;= \beta_0 + \beta_1 \cdot \text{xwOBA}^{\text{Batter}}_{ij} + \beta_2 \cdot \text{xwOBA}^{\text{Next Batter}}_{ij} \\&amp;\quad + \beta_3 \cdot \text{Matchup}^{\text{Current}}_{ij} + \beta_4 \cdot \text{Matchup}^{\text{Next}}_{ij} \\&amp;\quad + \beta_5 \cdot \text{Baserunners}_{ij} + \beta_6 \cdot \text{Outs}_{ij} \\&amp;\quad + \beta_7 \cdot \text{RunDiff}_{ij} \\&amp;\quad + u_{0, \text{PitcherYear}_j} + u_{1, \text{PitcherYear}_j} \cdot \text{xwOBA}^{\text{Next Batter}}_{ij} + \varepsilon_{ij}\end{align*}
\]</span></p>
<p>As seen in Table 1, the rest of the coefficients are similar to Model 1. The coefficient of <code>next_batter_xwOBA</code> is now -0.0307, and is negative and significant at the <span class="math inline">\(\alpha\)</span> = 0.05 level. In this model, run differential has become insignificant, but having a runner at 3rd base also now has a significant positive coefficient of 0.0071, indicating that having a runner at 3rd base increases the xwOBA of the current plate appearance compared to having nobody on base.</p>
<section id="a.-inspection-of-the-random-effects-for-xwoba" class="level4">
<h4 class="anchored" data-anchor-id="a.-inspection-of-the-random-effects-for-xwoba">A. Inspection of the Random Effects for xwOBA</h4>
<p>In order to get an indication of whether these random slopes are important and not just a product of random noise, we can look at the random effects of the model. We can do this by looking at the random slopes for the next batter’s xwOBA for each pitcher-year combination.</p>
<p>To get a better sense of the continuity of these random slopes–i.e.&nbsp;do certain pitchers have consistently high or low slopes across years–we can look at the correlation of these random slopes across years. We can do this by taking the random slopes for each pitcher-year combination and correlating them with the random slopes for the next batter’s xwOBA in the following year. We do this for all year pairings from 2015 to 2024, excluding 2020 due to limited sample size</p>
<p><strong>Figure 1</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="outputs/yoy_correlation_plot.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>All of these Year-Over-Year correlations are positive and greater than 0.25, except for 2019 to 2021, which is still positive and significantly greater than 0. This indicates that the random slopes for the next batter’s xwOBA are relatively stable over time, and that pitchers who are more affected by the next batter’s xwOBA in one year are likely to be similarly affected in the following year. This implies that the effect of the next batter’s xwOBA is not just a product of random noise, but rather a consistent pattern across pitchers.</p>
<p>We can graph the most recent year pair (2023 to 2024) to visualize the relationship between the random slopes for the next batter’s xwOBA in those two years.</p>
<p><strong>Figure 2</strong></p>
<iframe src="../../outputs/yoy_correlation_plotly.html" width="100%" height="600px" style="border:none;"></iframe>
<p style="font-size: 0.9em; font-style: italic;">
This interactive plot displays the relationship between pitcher-specific random slopes for the next batter’s xwOBA across 2023 and 2024.<br> Hover to explore individual pitchers, their IDs, and their sensitivity to lineup protection over time.
</p>
<p>Although these slopes seem to point to a clear observation of pitcher’s underlying sensitivities to lineup protection, we can also perform t-tests on each correlation to see if it is significantly greater than 0.</p>
<p><strong>Table 2</strong></p>



<meta charset="utf-8">
<style>body{background-color:white;}</style>




<div id="zivxvvpnsa" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>#zivxvvpnsa table {
  font-family: Times;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zivxvvpnsa thead, #zivxvvpnsa tbody, #zivxvvpnsa tfoot, #zivxvvpnsa tr, #zivxvvpnsa td, #zivxvvpnsa th {
  border-style: none;
}

#zivxvvpnsa p {
  margin: 0;
  padding: 0;
}

#zivxvvpnsa .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zivxvvpnsa .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zivxvvpnsa .gt_title {
  color: #333333;
  font-size: 14px;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zivxvvpnsa .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zivxvvpnsa .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zivxvvpnsa .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zivxvvpnsa .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zivxvvpnsa .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zivxvvpnsa .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zivxvvpnsa .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zivxvvpnsa .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zivxvvpnsa .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zivxvvpnsa .gt_spanner_row {
  border-bottom-style: hidden;
}

#zivxvvpnsa .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zivxvvpnsa .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zivxvvpnsa .gt_from_md > :first-child {
  margin-top: 0;
}

#zivxvvpnsa .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zivxvvpnsa .gt_row {
  padding-top: 6px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zivxvvpnsa .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zivxvvpnsa .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zivxvvpnsa .gt_row_group_first td {
  border-top-width: 2px;
}

#zivxvvpnsa .gt_row_group_first th {
  border-top-width: 2px;
}

#zivxvvpnsa .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zivxvvpnsa .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zivxvvpnsa .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zivxvvpnsa .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zivxvvpnsa .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zivxvvpnsa .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zivxvvpnsa .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zivxvvpnsa .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zivxvvpnsa .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zivxvvpnsa .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zivxvvpnsa .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zivxvvpnsa .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zivxvvpnsa .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zivxvvpnsa .gt_left {
  text-align: left;
}

#zivxvvpnsa .gt_center {
  text-align: center;
}

#zivxvvpnsa .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zivxvvpnsa .gt_font_normal {
  font-weight: normal;
}

#zivxvvpnsa .gt_font_bold {
  font-weight: bold;
}

#zivxvvpnsa .gt_font_italic {
  font-style: italic;
}

#zivxvvpnsa .gt_super {
  font-size: 65%;
}

#zivxvvpnsa .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zivxvvpnsa .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zivxvvpnsa .gt_indent_1 {
  text-indent: 5px;
}

#zivxvvpnsa .gt_indent_2 {
  text-indent: 10px;
}

#zivxvvpnsa .gt_indent_3 {
  text-indent: 15px;
}

#zivxvvpnsa .gt_indent_4 {
  text-indent: 20px;
}

#zivxvvpnsa .gt_indent_5 {
  text-indent: 25px;
}
</style>
  
<table class="gt_table caption-top table" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="5" class="gt_heading gt_title gt_font_normal"><strong>One-Sided t-Tests for Year-over-Year Correlation of Random Slopes</strong></th>
</tr>
<tr class="gt_heading even">
<th colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Each test evaluates whether the correlation between random slopes for a given year pair is significantly greater than 0.</th>
</tr>
<tr class="gt_col_headings header">
<th id="Year Pair" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Year Pair</th>
<th id="Correlation" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Correlation</th>
<th id="t Statistic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">t Statistic</th>
<th id="Degrees of Freedom" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Degrees of Freedom</th>
<th id="p-value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">p-value</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="year_pair">2015 to 2016</td>
<td class="gt_row gt_right" headers="correlation">0.395</td>
<td class="gt_row gt_right" headers="t_stat">6.37</td>
<td class="gt_row gt_right" headers="df">219</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="year_pair">2016 to 2017</td>
<td class="gt_row gt_right" headers="correlation">0.374</td>
<td class="gt_row gt_right" headers="t_stat">5.96</td>
<td class="gt_row gt_right" headers="df">218</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="year_pair">2017 to 2018</td>
<td class="gt_row gt_right" headers="correlation">0.365</td>
<td class="gt_row gt_right" headers="t_stat">5.51</td>
<td class="gt_row gt_right" headers="df">198</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="year_pair">2018 to 2019</td>
<td class="gt_row gt_right" headers="correlation">0.375</td>
<td class="gt_row gt_right" headers="t_stat">5.47</td>
<td class="gt_row gt_right" headers="df">183</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="year_pair">2019 to 2021</td>
<td class="gt_row gt_right" headers="correlation">0.216</td>
<td class="gt_row gt_right" headers="t_stat">2.55</td>
<td class="gt_row gt_right" headers="df">133</td>
<td class="gt_row gt_right" headers="p_value">0.006</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="year_pair">2021 to 2022</td>
<td class="gt_row gt_right" headers="correlation">0.317</td>
<td class="gt_row gt_right" headers="t_stat">4.48</td>
<td class="gt_row gt_right" headers="df">180</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="year_pair">2022 to 2023</td>
<td class="gt_row gt_right" headers="correlation">0.329</td>
<td class="gt_row gt_right" headers="t_stat">4.79</td>
<td class="gt_row gt_right" headers="df">189</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="year_pair">2023 to 2024</td>
<td class="gt_row gt_right" headers="correlation">0.261</td>
<td class="gt_row gt_right" headers="t_stat">3.80</td>
<td class="gt_row gt_right" headers="df">197</td>
<td class="gt_row gt_right" headers="p_value">0.000</td>
</tr>
</tbody>
</table>

</div>


<p style="font-size: 0.9em; font-style: italic;">
One-sample t-tests were conducted for each year-to-year correlation, testing whether it is significantly greater than 0.
</p>
<p>Because all of these have significant p-values, we can confidently say that the year-over-year correlations in random slopes are not the result of random noise, but instead reflect persistent individual-level differences in pitcher sensitivity to lineup protection. This also means that studying individual pitcher’s susceptibility to lineup protection is a worthwhile endeavor.</p>
<p><strong>Table 3</strong></p>



<meta charset="utf-8">
<style>body{background-color:white;}</style>




<div id="cfjigbfagk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>#cfjigbfagk table {
  font-family: Times;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cfjigbfagk thead, #cfjigbfagk tbody, #cfjigbfagk tfoot, #cfjigbfagk tr, #cfjigbfagk td, #cfjigbfagk th {
  border-style: none;
}

#cfjigbfagk p {
  margin: 0;
  padding: 0;
}

#cfjigbfagk .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cfjigbfagk .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cfjigbfagk .gt_title {
  color: #333333;
  font-size: 14px;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cfjigbfagk .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cfjigbfagk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cfjigbfagk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cfjigbfagk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cfjigbfagk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cfjigbfagk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cfjigbfagk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cfjigbfagk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cfjigbfagk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cfjigbfagk .gt_spanner_row {
  border-bottom-style: hidden;
}

#cfjigbfagk .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cfjigbfagk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cfjigbfagk .gt_from_md > :first-child {
  margin-top: 0;
}

#cfjigbfagk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cfjigbfagk .gt_row {
  padding-top: 6px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cfjigbfagk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cfjigbfagk .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cfjigbfagk .gt_row_group_first td {
  border-top-width: 2px;
}

#cfjigbfagk .gt_row_group_first th {
  border-top-width: 2px;
}

#cfjigbfagk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cfjigbfagk .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cfjigbfagk .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cfjigbfagk .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cfjigbfagk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cfjigbfagk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cfjigbfagk .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cfjigbfagk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cfjigbfagk .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cfjigbfagk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cfjigbfagk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cfjigbfagk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cfjigbfagk .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cfjigbfagk .gt_left {
  text-align: left;
}

#cfjigbfagk .gt_center {
  text-align: center;
}

#cfjigbfagk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cfjigbfagk .gt_font_normal {
  font-weight: normal;
}

#cfjigbfagk .gt_font_bold {
  font-weight: bold;
}

#cfjigbfagk .gt_font_italic {
  font-style: italic;
}

#cfjigbfagk .gt_super {
  font-size: 65%;
}

#cfjigbfagk .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cfjigbfagk .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cfjigbfagk .gt_indent_1 {
  text-indent: 5px;
}

#cfjigbfagk .gt_indent_2 {
  text-indent: 10px;
}

#cfjigbfagk .gt_indent_3 {
  text-indent: 15px;
}

#cfjigbfagk .gt_indent_4 {
  text-indent: 20px;
}

#cfjigbfagk .gt_indent_5 {
  text-indent: 25px;
}
</style>
  
<table class="gt_table caption-top table" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="5" class="gt_heading gt_title gt_font_normal"><strong>Top 10 Pitchers Negatively Affected by Lineup Protection (2024)</strong></th>
</tr>
<tr class="gt_heading even">
<th colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Ranked by Random Slope on Next Batter xwOBA</th>
</tr>
<tr class="gt_col_headings header">
<th id="First Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">First Name</th>
<th id="Last Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Last Name</th>
<th id="MLBAM ID" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">MLBAM ID</th>
<th id="Random Slope" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Random Slope</th>
<th id="Plate Appearances" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Plate Appearances</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Roddery</td>
<td class="gt_row gt_left" headers="name_last">Muñoz</td>
<td class="gt_row gt_center" headers="pitcher">682610</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0754</td>
<td class="gt_row gt_right" headers="pa_count">209</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Martín</td>
<td class="gt_row gt_left" headers="name_last">Pérez</td>
<td class="gt_row gt_center" headers="pitcher">527048</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0639</td>
<td class="gt_row gt_right" headers="pa_count">243</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Taijuan</td>
<td class="gt_row gt_left" headers="name_last">Walker</td>
<td class="gt_row gt_center" headers="pitcher">592836</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0638</td>
<td class="gt_row gt_right" headers="pa_count">180</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Randy</td>
<td class="gt_row gt_left" headers="name_last">Vásquez</td>
<td class="gt_row gt_center" headers="pitcher">681190</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0526</td>
<td class="gt_row gt_right" headers="pa_count">306</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Emerson</td>
<td class="gt_row gt_left" headers="name_last">Hancock</td>
<td class="gt_row gt_center" headers="pitcher">676106</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0464</td>
<td class="gt_row gt_right" headers="pa_count">140</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Jon</td>
<td class="gt_row gt_left" headers="name_last">Gray</td>
<td class="gt_row gt_center" headers="pitcher">592351</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0433</td>
<td class="gt_row gt_right" headers="pa_count">248</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Valente</td>
<td class="gt_row gt_left" headers="name_last">Bellozo</td>
<td class="gt_row gt_center" headers="pitcher">678368</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0410</td>
<td class="gt_row gt_right" headers="pa_count">152</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Anthony</td>
<td class="gt_row gt_left" headers="name_last">Molina</td>
<td class="gt_row gt_center" headers="pitcher">683627</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0406</td>
<td class="gt_row gt_right" headers="pa_count">100</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Kenta</td>
<td class="gt_row gt_left" headers="name_last">Maeda</td>
<td class="gt_row gt_center" headers="pitcher">628317</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0392</td>
<td class="gt_row gt_right" headers="pa_count">222</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Kyle</td>
<td class="gt_row gt_left" headers="name_last">Gibson</td>
<td class="gt_row gt_center" headers="pitcher">502043</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">0.0375</td>
<td class="gt_row gt_right" headers="pa_count">412</td>
</tr>
</tbody>
</table>

</div>


<p><strong>Table 4</strong></p>



<meta charset="utf-8">
<style>body{background-color:white;}</style>




<div id="xmsoqqhkqe" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>#xmsoqqhkqe table {
  font-family: Times;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xmsoqqhkqe thead, #xmsoqqhkqe tbody, #xmsoqqhkqe tfoot, #xmsoqqhkqe tr, #xmsoqqhkqe td, #xmsoqqhkqe th {
  border-style: none;
}

#xmsoqqhkqe p {
  margin: 0;
  padding: 0;
}

#xmsoqqhkqe .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xmsoqqhkqe .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xmsoqqhkqe .gt_title {
  color: #333333;
  font-size: 14px;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xmsoqqhkqe .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xmsoqqhkqe .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xmsoqqhkqe .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xmsoqqhkqe .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xmsoqqhkqe .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xmsoqqhkqe .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xmsoqqhkqe .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xmsoqqhkqe .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xmsoqqhkqe .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xmsoqqhkqe .gt_spanner_row {
  border-bottom-style: hidden;
}

#xmsoqqhkqe .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xmsoqqhkqe .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xmsoqqhkqe .gt_from_md > :first-child {
  margin-top: 0;
}

#xmsoqqhkqe .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xmsoqqhkqe .gt_row {
  padding-top: 6px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xmsoqqhkqe .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xmsoqqhkqe .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xmsoqqhkqe .gt_row_group_first td {
  border-top-width: 2px;
}

#xmsoqqhkqe .gt_row_group_first th {
  border-top-width: 2px;
}

#xmsoqqhkqe .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xmsoqqhkqe .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xmsoqqhkqe .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xmsoqqhkqe .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xmsoqqhkqe .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xmsoqqhkqe .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xmsoqqhkqe .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xmsoqqhkqe .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xmsoqqhkqe .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xmsoqqhkqe .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xmsoqqhkqe .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xmsoqqhkqe .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xmsoqqhkqe .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xmsoqqhkqe .gt_left {
  text-align: left;
}

#xmsoqqhkqe .gt_center {
  text-align: center;
}

#xmsoqqhkqe .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xmsoqqhkqe .gt_font_normal {
  font-weight: normal;
}

#xmsoqqhkqe .gt_font_bold {
  font-weight: bold;
}

#xmsoqqhkqe .gt_font_italic {
  font-style: italic;
}

#xmsoqqhkqe .gt_super {
  font-size: 65%;
}

#xmsoqqhkqe .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xmsoqqhkqe .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xmsoqqhkqe .gt_indent_1 {
  text-indent: 5px;
}

#xmsoqqhkqe .gt_indent_2 {
  text-indent: 10px;
}

#xmsoqqhkqe .gt_indent_3 {
  text-indent: 15px;
}

#xmsoqqhkqe .gt_indent_4 {
  text-indent: 20px;
}

#xmsoqqhkqe .gt_indent_5 {
  text-indent: 25px;
}
</style>
  
<table class="gt_table caption-top table" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="5" class="gt_heading gt_title gt_font_normal"><strong>Top 10 Pitchers Positively Affected by Lineup Protection (2024)</strong></th>
</tr>
<tr class="gt_heading even">
<th colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Ranked by Random Slope on Next Batter xwOBA</th>
</tr>
<tr class="gt_col_headings header">
<th id="First Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">First Name</th>
<th id="Last Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Last Name</th>
<th id="MLBAM ID" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">MLBAM ID</th>
<th id="Random Slope" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Random Slope</th>
<th id="Plate Appearances" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Plate Appearances</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Tyler</td>
<td class="gt_row gt_left" headers="name_last">Glasnow</td>
<td class="gt_row gt_center" headers="pitcher">607192</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0680</td>
<td class="gt_row gt_right" headers="pa_count">284</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Mason</td>
<td class="gt_row gt_left" headers="name_last">Miller</td>
<td class="gt_row gt_center" headers="pitcher">695243</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0616</td>
<td class="gt_row gt_right" headers="pa_count">103</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Paul</td>
<td class="gt_row gt_left" headers="name_last">Skenes</td>
<td class="gt_row gt_center" headers="pitcher">694973</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0530</td>
<td class="gt_row gt_right" headers="pa_count">300</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Raisel</td>
<td class="gt_row gt_left" headers="name_last">Iglesias</td>
<td class="gt_row gt_center" headers="pitcher">628452</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0510</td>
<td class="gt_row gt_right" headers="pa_count">104</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Bryan</td>
<td class="gt_row gt_left" headers="name_last">Woo</td>
<td class="gt_row gt_center" headers="pitcher">693433</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0502</td>
<td class="gt_row gt_right" headers="pa_count">217</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Justin</td>
<td class="gt_row gt_left" headers="name_last">Steele</td>
<td class="gt_row gt_center" headers="pitcher">657006</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0482</td>
<td class="gt_row gt_right" headers="pa_count">246</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Joe</td>
<td class="gt_row gt_left" headers="name_last">Jiménez</td>
<td class="gt_row gt_center" headers="pitcher">641729</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0467</td>
<td class="gt_row gt_right" headers="pa_count">138</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Ryan</td>
<td class="gt_row gt_left" headers="name_last">Walker</td>
<td class="gt_row gt_center" headers="pitcher">676254</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0457</td>
<td class="gt_row gt_right" headers="pa_count">137</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="name_first">Carlos</td>
<td class="gt_row gt_left" headers="name_last">Rodón</td>
<td class="gt_row gt_center" headers="pitcher">607074</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0431</td>
<td class="gt_row gt_right" headers="pa_count">323</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="name_first">Sean</td>
<td class="gt_row gt_left" headers="name_last">Hjelle</td>
<td class="gt_row gt_center" headers="pitcher">663546</td>
<td class="gt_row gt_right" headers="next_batter_xwOBA">−0.0425</td>
<td class="gt_row gt_right" headers="pa_count">145</td>
</tr>
</tbody>
</table>

</div>


<p>In 2024, the random slopes on next_batter_xwOBA reveal how individual pitchers deviated from the average lineup protection effect—where the fixed effect of next_batter_xwOBA was negative, indicating that pitchers tend to allow lower expected outcomes when a strong hitter is looming. At the top of the slope distribution, pitchers like Roddery Muñoz, Martín Pérez, and Randy Vásquez had positive random slopes, meaning the usual lineup protection suppression effect was less true for them—or even reversed. These pitchers were more susceptible to lineup protection (the pitcher’s expected outcomes (xwOBA) get worse when the next batter is stronger).</p>
<p>In contrast, pitchers like Tyler Glasnow, Paul Skenes, and Bryan Woo had even more negative slopes than average, suggesting they are especially effective at suppressing outcomes when a strong next batter is present. These pitchers were less affected (or may even pitch better) in those scenarios where a stronger batter is on deck.</p>
<p>It is worth noting that although some of the league’s best pitchers (like Glasnow and Skenes) are at the bottom of this list, this does not mean that these lists are simply a ranking of pitcher quality. The random slopes are not correlated with the fixed effect of <code>next_batter_xwOBA</code>, and thus, a pitcher can be very good and still have a positive random slope. This is because the random slope is measuring how much the pitcher deviates from the average lineup protection effect, not how good they are overall with lineup protection.</p>
<p>So, when we see some of the leagues best pitchers at the bottom of this list, it means that one of their skills is to be able to pitch well regardless of the next batter’s quality, and potentially even better when there is a threat looming.</p>
<p><strong>Takeaway:</strong> Some of the league’s best pitchers perform better when a strong hitter is on deck, serving as an indication of mental aptitude or ability to elevate in high-leverage moments that makes them so successful. This suggests that the effects of lineup protection/penalty may not be a universal phenomenon and that individual pitchers may have different responses to it.</p>
</section>
<section id="b.-drivers-of-the-overall-offensive-effect" class="level4">
<h4 class="anchored" data-anchor-id="b.-drivers-of-the-overall-offensive-effect">B. Drivers of the Overall Offensive Effect</h4>
<p>To better understand why the coefficient for next_batter_xwOBA in our main model is negative and significant, we decomposed offensive outcomes into their core components. Following previous research conventions, we modeled five binary outcome categories: walks, strikeouts, extra-base hits (XBH), singles, and in-play outs (IPO). Each category was modeled using a fixed-effects logistic regression, accounting for game state, matchup variables, and base-out situations.</p>
<p><strong>Table 5</strong></p>
<table class="texreg caption-top table" data-quarto-postprocess="true">
<caption>Table: Fixed-Effects Linear Models Predicting Distinct PA Events</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Walk</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Strikeout</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">XBH</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Single</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">In-Play Out</th>
</tr>
</thead>
<tbody>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">-0.5207 (0.1790)<sup>**</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0677 (0.1224)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.3503 (0.1742)<sup>*</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0580 (0.1342)</td>
<td style="padding-left: 5px; padding-right: 5px">0.3293 (0.1025)<sup>**</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Current Matchup</td>
<td style="padding-left: 5px; padding-right: 5px">0.2584 (0.0120)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1162 (0.0089)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.2269 (0.0115)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0352 (0.0090)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1267 (0.0068)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Next Matchup</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0080 (0.0103)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0047 (0.0072)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0172 (0.0099)<sup>·</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0208 (0.0078)<sup>**</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0118 (0.0060)<sup>*</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">1B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.1537 (0.0123)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1386 (0.0081)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0204 (0.0112)<sup>·</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.1209 (0.0086)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0827 (0.0067)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B-2B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.1025 (0.0178)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1004 (0.0127)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0202 (0.0175)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0143 (0.0138)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0678 (0.0102)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">1B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.2011 (0.0277)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.2255 (0.0189)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0302 (0.0261)</td>
<td style="padding-left: 5px; padding-right: 5px">0.1519 (0.0193)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.4526 (0.0146)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">2B</td>
<td style="padding-left: 5px; padding-right: 5px">0.3701 (0.0148)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0898 (0.0110)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1290 (0.0158)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0213 (0.0127)<sup>·</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1816 (0.0091)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">2B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.3822 (0.0276)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1094 (0.0209)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1107 (0.0314)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0224 (0.0237)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.5201 (0.0169)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.3437 (0.0239)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1229 (0.0184)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0642 (0.0270)<sup>*</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0676 (0.0203)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.4711 (0.0148)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Loaded</td>
<td style="padding-left: 5px; padding-right: 5px">-0.3424 (0.0323)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.1412 (0.0212)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.1135 (0.0282)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0641 (0.0226)<sup>**</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.3655 (0.0169)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Outs</td>
<td style="padding-left: 5px; padding-right: 5px">0.1075 (0.0054)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0600 (0.0036)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0407 (0.0051)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0424 (0.0041)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0548 (0.0032)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Run Diff</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0003 (0.0015)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0021 (0.0011)<sup>·</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0054 (0.0015)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0023 (0.0012)<sup>·</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0018 (0.0009)<sup>*</sup></td>
</tr>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Num. obs.</td>
<td style="padding-left: 5px; padding-right: 5px">784300</td>
<td style="padding-left: 5px; padding-right: 5px">788241</td>
<td style="padding-left: 5px; padding-right: 5px">784619</td>
<td style="padding-left: 5px; padding-right: 5px">788133</td>
<td style="padding-left: 5px; padding-right: 5px">788241</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: batter_year</td>
<td style="padding-left: 5px; padding-right: 5px">3519</td>
<td style="padding-left: 5px; padding-right: 5px">3578</td>
<td style="padding-left: 5px; padding-right: 5px">3526</td>
<td style="padding-left: 5px; padding-right: 5px">3577</td>
<td style="padding-left: 5px; padding-right: 5px">3578</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: pitcher_year</td>
<td style="padding-left: 5px; padding-right: 5px">5395</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
<td style="padding-left: 5px; padding-right: 5px">5393</td>
<td style="padding-left: 5px; padding-right: 5px">5422</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Deviance</td>
<td style="padding-left: 5px; padding-right: 5px">427363.3039</td>
<td style="padding-left: 5px; padding-right: 5px">768920.5207</td>
<td style="padding-left: 5px; padding-right: 5px">443158.7544</td>
<td style="padding-left: 5px; padding-right: 5px">646537.5143</td>
<td style="padding-left: 5px; padding-right: 5px">998098.5332</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Log Likelihood</td>
<td style="padding-left: 5px; padding-right: 5px">-213681.6519</td>
<td style="padding-left: 5px; padding-right: 5px">-384460.2603</td>
<td style="padding-left: 5px; padding-right: 5px">-221579.3772</td>
<td style="padding-left: 5px; padding-right: 5px">-323268.7572</td>
<td style="padding-left: 5px; padding-right: 5px">-499049.2666</td>
</tr>
<tr class="even" style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Pseudo R<sup>2</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0122</td>
<td style="padding-left: 5px; padding-right: 5px">0.0229</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0088</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0042</td>
<td style="padding-left: 5px; padding-right: 5px">0.0003</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="6" style="font-size: 0.8em">Standard errors in parentheses. *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05, . p &lt; 0.1</td>
</tr>
</tfoot>

</table>
<p>We can focus on these five outcomes independently. Throughout these models, many baserunner states and our Outs variable have significant coefficients, but these are rather difficult to piece together for proper analysis.</p>
<p><strong>Walks</strong>: The coefficient for the next batter’s xwOBA is negative and significant at the 1% level (−0.5207,SE=0.1790). This suggests that when a stronger hitter is on deck, pitchers are less likely to pitch around the current batter, reducing walk probability. This aligns closely with the theoretical foundations of lineup protection—pitchers are incentivized to attack the current batter if the next one is also a threat.</p>
<p><strong>Strikeouts</strong>: The coefficient for the next batter’s xwOBA on strikeouts is small and not statistically significant (0.0677,SE=0.1224). This implies that the quality of the on-deck hitter does not substantially influence the pitcher’s ability (or decision) to induce a strikeout. It’s likely that this outcome is more driven by the current batter’s own contact and swing profiles than by lineup context. It is worth noting that, as expected, the current batter having a favorable handedness matchup has a significant negative effect on the ability for that pitcher to get a strikeout.</p>
<p><strong>Extra-Base Hits (XBH)</strong>: Here, the coefficient for the next batter’s xwOBA has a negative and significant effect (−0.3503,SE=0.1742), indicating that better hitters on deck reduce the likelihood of the current batter recording an extra-base hit. This could reflect more aggressive pitching strategies (e.g., fewer mistake pitches or fewer favorable counts) in high-leverage lineup situations. It also potentially explains a portion of the overall negative xwOBA association observed earlier. This is contrary to the research of Phillips (2011), but could be due to the fact that we are using a different definition of lineup protection, as that article considered lineup protection ot be a binary variable, while we are treating it as a continuous variable.</p>
<p><strong>Singles</strong>: In the singles model, the coefficient for the next batter’s xwOBA is not statistically significant (−0.0580,SE=0.1342). We originally used a broader <code>is_hit</code> outcome variable, but its interpretation was confounded by the inclusion of XBH. Focusing on singles alone provides cleaner insight. This is consistent with the idea that singles are more random and luck-induced and less influenced by the pitcher’s strategy or the current game context. It is also worth noting that the next hitter having a matchup advantage is positive and significant (0.0208, SE=0.0078), which could be a result of just having a lot of data. One theory as to why this is the case is that when a batter knows that someone on deck has a matchup advantage, they may not try to do too much, and instead just try to get on base, which would lead to more singles.</p>
<p><strong>In-Play Outs</strong>: Interestingly, the coefficient for the next batter’s xwOBA is positive and significant (0.3293, SE = 0.1025), suggesting that better hitters on deck increase the probability of an in-play out for the current batter. This may reflect pitchers throwing more hittable pitches (reducing walks), but also locating them more effectively or strategically, resulting in weak contact or outs. Together with the XBH result, this supports the idea that lineup protection doesn’t make hitters more dangerous—if anything, it suppresses high-value outcomes while increasing weak contact.</p>
<p><strong>Takeaway:</strong> While overall offensive outcomes are negatively impacted by the next batter’s xwOBA, the underlying components of this effect align in part with previous research on lineup protection. These component models reinforce the central finding from our mixed-effects model: lineup protection, as proxied by next_batter_xwOBA, exerts a small but measurable negative effect on the current batter’s expected value. The clearest mechanisms appear to be a reduction in walks and suppression of extra-base hits, paired with an increase in weak contact leading to outs, while singles are not significantly affected. These results suggest that the quality of the next batter influences the pitcher’s approach—leading to fewer walks and more aggressive strategies that ultimately reduce the likelihood of high-value offensive outcomes for the current hitter.</p>
</section>
</section>
<section id="ii.-increased-interpretability-fixed-effects-linear-model-on-xba" class="level3">
<h3 class="anchored" data-anchor-id="ii.-increased-interpretability-fixed-effects-linear-model-on-xba">II. Increased Interpretability: Fixed Effects Linear Model on xBA</h3>
<p>In order to increase interpretability, we will also look at the xBA of the current plate appearance. We will use the same model as above, but with <code>pa_xBA</code> as our outcome variable instead of <code>pa_xwOBA</code>.</p>
<p>This model examines how a plate appearance’s batting average metric (<code>pa_xBA</code>) depends on the batter, the following hitter’s season-long expected wOBA, and various other contextual factors. The results, shown in Table 6, reaffirm the findings from our xwOBA-based models while offering additional clarity.</p>
<p><strong>Table 6</strong></p>
<table class="texreg caption-top table" data-quarto-postprocess="true">
<caption>Table: Fixed-Effects Linear Model Predicting Expected Batting Average (xBA)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">xBA</th>
</tr>
</thead>
<tbody>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0329 (0.0160)<sup>*</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Current Matchup Advantage</td>
<td style="padding-left: 5px; padding-right: 5px">0.0174 (0.0011)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Next Matchup Advantage</td>
<td style="padding-left: 5px; padding-right: 5px">0.0015 (0.0010)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Runner on 1B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0066 (0.0011)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Runners on 1B &amp; 2B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0063 (0.0017)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Runners on 1B &amp; 3B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0066 (0.0025)<sup>**</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Runner on 2B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0062 (0.0016)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Runners on 2B &amp; 3B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0095 (0.0030)<sup>**</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Runner on 3B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0091 (0.0026)<sup>***</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Bases Loaded</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0038 (0.0027)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Outs When Up</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0017 (0.0005)<sup>**</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Run Differential</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0006 (0.0001)<sup>***</sup></td>
</tr>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Num. obs.</td>
<td style="padding-left: 5px; padding-right: 5px">543632</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: batter_year</td>
<td style="padding-left: 5px; padding-right: 5px">3578</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: pitcher_year</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0269</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0007</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0105</td>
</tr>
<tr class="odd" style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0007</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="2" style="font-size: 0.8em">Standard errors clustered by batter-year. *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05, . p &lt; 0.1</td>
</tr>
</tfoot>

</table>
<p>The coefficient for next_batter_xwOBA is negative and significant (−0.0329,SE=0.0160,p&lt;0.05), indicating that when a stronger hitter is on deck, the current batter’s expected batting average slightly decreases. Although the effect is small in absolute terms, it is statistically meaningful and consistent with the narrative that pitchers adopt more aggressive, run-suppressing strategies when a threat looms behind the current hitter.</p>
<p>Additionally, current matchup advantage (e.g., lefty batter vs.&nbsp;righty pitcher) is positively associated with xBA, (0.0174,SE=0.0011,p&lt;0.001), reinforcing that platoon advantages remain a key determinant of batting success. Interestingly, next matchup advantage is only marginally significant even though it was significant in our Singles model, suggesting that expected Batting Average outcomes are just a muddled version of the more specific outcomes.</p>
<p>The model explains a modest proportion of variance in xBA (<span class="math inline">\(R^2\)</span>=0.027), which is expected given the inherently stochastic nature of batted-ball outcomes and the granularity of pitch-by-pitch data.</p>
<p><strong>Takeaway:</strong> Even when controlling for batter skill, matchup effects, and game state, a higher next_batter_xwOBA is associated with a small but statistically significant decrease in the current batter’s expected batting average (xBA) for that plate appearance. If the next batter’s xwOBA goes up by 0.100, we estimate a ~-0.003 reduction in pa_xBA per plate appearance—over 500 plate appearances, that amounts to about 1.5 fewer expected hits compared to otherwise.</p>
</section>
<section id="iii.-model-selection-of-the-overall-offensive-output" class="level3">
<h3 class="anchored" data-anchor-id="iii.-model-selection-of-the-overall-offensive-output">III. Model Selection of the Overall Offensive Output</h3>
<p>To determine which model to move forward with, we then found the root-mean-squared-errors (RMSE) of Model 1 (Fixed Effects OLS) and Model 3 (Mixed Effects with Random Slope), and found that with 5-fold Cross Validation, Model 1 has an estimated RMSE of 0.383, while Model 3 has an estimated RMSE of 0.381. Because of the computational limitations of doing Fixed Effects OLS to find exact log-likelihood ratios, we will use Model 3 to do model selection.</p>
<p>To assess the contribution of each predictor in our mixed-effects model (<code>m_protection_slope</code>), we used the <code>drop1()</code> function, which conducts likelihood ratio tests by sequentially dropping one term at a time. This method compares the full model to a nested version with a single predictor removed, estimating whether that term significantly improves the model’s fit to the data. A significant test result indicates that the predictor explains meaningful variation in the outcome variable (<code>pa_xwOBA</code>) beyond what is captured by other variables.</p>
<p><strong>Table 7</strong></p>



<meta charset="utf-8">
<style>body{background-color:white;}</style>




<div id="ddfunnccdi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>@import url("https://fonts.googleapis.com/css2?family=Times+New+Roman:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#ddfunnccdi table {
  font-family: 'Times New Roman', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ddfunnccdi thead, #ddfunnccdi tbody, #ddfunnccdi tfoot, #ddfunnccdi tr, #ddfunnccdi td, #ddfunnccdi th {
  border-style: none;
}

#ddfunnccdi p {
  margin: 0;
  padding: 0;
}

#ddfunnccdi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ddfunnccdi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ddfunnccdi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ddfunnccdi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ddfunnccdi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ddfunnccdi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ddfunnccdi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ddfunnccdi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ddfunnccdi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ddfunnccdi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ddfunnccdi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ddfunnccdi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ddfunnccdi .gt_spanner_row {
  border-bottom-style: hidden;
}

#ddfunnccdi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ddfunnccdi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ddfunnccdi .gt_from_md > :first-child {
  margin-top: 0;
}

#ddfunnccdi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ddfunnccdi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ddfunnccdi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ddfunnccdi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ddfunnccdi .gt_row_group_first td {
  border-top-width: 2px;
}

#ddfunnccdi .gt_row_group_first th {
  border-top-width: 2px;
}

#ddfunnccdi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ddfunnccdi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ddfunnccdi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ddfunnccdi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ddfunnccdi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ddfunnccdi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ddfunnccdi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ddfunnccdi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ddfunnccdi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ddfunnccdi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ddfunnccdi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ddfunnccdi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ddfunnccdi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ddfunnccdi .gt_left {
  text-align: left;
}

#ddfunnccdi .gt_center {
  text-align: center;
}

#ddfunnccdi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ddfunnccdi .gt_font_normal {
  font-weight: normal;
}

#ddfunnccdi .gt_font_bold {
  font-weight: bold;
}

#ddfunnccdi .gt_font_italic {
  font-style: italic;
}

#ddfunnccdi .gt_super {
  font-size: 65%;
}

#ddfunnccdi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ddfunnccdi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ddfunnccdi .gt_indent_1 {
  text-indent: 5px;
}

#ddfunnccdi .gt_indent_2 {
  text-indent: 10px;
}

#ddfunnccdi .gt_indent_3 {
  text-indent: 15px;
}

#ddfunnccdi .gt_indent_4 {
  text-indent: 20px;
}

#ddfunnccdi .gt_indent_5 {
  text-indent: 25px;
}
</style>
  
<table class="gt_table caption-top table" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="8" class="gt_heading gt_title gt_font_normal"><strong>Fixed Effect Importance via Drop-One F-tests</strong></th>
</tr>
<tr class="gt_heading even">
<th colspan="8" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Each test evaluates whether removing the fixed effect significantly worsens model fit</th>
</tr>
<tr class="gt_col_headings header">
<th id="Dropped Term" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Dropped Term</th>
<th id="Sum Sq" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Sum Sq</th>
<th id="Mean Sq" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Mean Sq</th>
<th id="Num DF" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Num DF</th>
<th id="Den DF" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Den DF</th>
<th id="F Statistic" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">F Statistic</th>
<th id="p-value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">p-value</th>
<th id="Signif." class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Signif.</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_center" headers="Dropped Term">Batter xwOBA</td>
<td class="gt_row gt_center" headers="Sum Sq">916.69</td>
<td class="gt_row gt_center" headers="Mean Sq">916.69</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">618,710</td>
<td class="gt_row gt_center" headers="F value">6,325.86</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.00</td>
<td class="gt_row gt_center" headers="Signif.">***</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="Dropped Term">Next Batter xwOBA</td>
<td class="gt_row gt_center" headers="Sum Sq">0.77</td>
<td class="gt_row gt_center" headers="Mean Sq">0.77</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">131,840</td>
<td class="gt_row gt_center" headers="F value">5.29</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.02</td>
<td class="gt_row gt_center" headers="Signif.">*</td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="Dropped Term">Current Matchup</td>
<td class="gt_row gt_center" headers="Sum Sq">52.81</td>
<td class="gt_row gt_center" headers="Mean Sq">52.81</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">368,484</td>
<td class="gt_row gt_center" headers="F value">364.40</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.00</td>
<td class="gt_row gt_center" headers="Signif.">***</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="Dropped Term">Next Matchup</td>
<td class="gt_row gt_center" headers="Sum Sq">0.11</td>
<td class="gt_row gt_center" headers="Mean Sq">0.11</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">330,949</td>
<td class="gt_row gt_center" headers="F value">0.75</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.39</td>
<td class="gt_row gt_center" headers="Signif."></td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="Dropped Term">Baserunner State</td>
<td class="gt_row gt_center" headers="Sum Sq">2.51</td>
<td class="gt_row gt_center" headers="Mean Sq">0.36</td>
<td class="gt_row gt_center" headers="NumDF">7</td>
<td class="gt_row gt_center" headers="DenDF">621,862</td>
<td class="gt_row gt_center" headers="F value">2.47</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.02</td>
<td class="gt_row gt_center" headers="Signif.">*</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="Dropped Term">Outs</td>
<td class="gt_row gt_center" headers="Sum Sq">7.29</td>
<td class="gt_row gt_center" headers="Mean Sq">7.29</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">621,667</td>
<td class="gt_row gt_center" headers="F value">50.30</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.00</td>
<td class="gt_row gt_center" headers="Signif.">***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="Dropped Term">Run Diff</td>
<td class="gt_row gt_center" headers="Sum Sq">0.05</td>
<td class="gt_row gt_center" headers="Mean Sq">0.05</td>
<td class="gt_row gt_center" headers="NumDF">1</td>
<td class="gt_row gt_center" headers="DenDF">446,230</td>
<td class="gt_row gt_center" headers="F value">0.38</td>
<td class="gt_row gt_center" headers="Pr(>F)">0.54</td>
<td class="gt_row gt_center" headers="Signif."></td>
</tr>
</tbody><tfoot class="gt_sourcenotes">
<tr class="odd">
<td colspan="8" class="gt_sourcenote">Significance codes: *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05, . p &lt; 0.1</td>
</tr>
</tfoot>

</table>

</div>


<p>Given this output, we can exclude Next Matchup Advantage and Run Differential from our final model, given that they do not significantly worsen model fit when they are omitted.</p>
<p>We will create two final models: <code>m_protection_blog_1_fe</code> and <code>m_protection_blog1_re</code>, using just the variables whose removal significantly worsened model fit.</p>
<p><strong>Table 8</strong></p>
<table class="texreg caption-top table" data-quarto-postprocess="true">
<caption>Comparison of Fixed and Random Effects Models for Plate Appearance xwOBA</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Model 1: Fixed Effects</th>
<th data-quarto-table-cell-role="th" style="padding-left: 5px; padding-right: 5px">Model 2: Random Effects</th>
</tr>
</thead>
<tbody>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Intercept</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.0001 (0.0054)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">1.0182 (0.0128)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0435 (0.0177)<sup>*</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0308 (0.0133)<sup>*</sup></td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Current Matchup</td>
<td style="padding-left: 5px; padding-right: 5px">0.0318 (0.0012)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0192 (0.0010)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0005 (0.0012)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0015 (0.0013)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">1B-2B</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0007 (0.0018)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0010 (0.0021)</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">1B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0025 (0.0027)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0028 (0.0031)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">2B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0057 (0.0016)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">0.0061 (0.0018)<sup>***</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">2B-3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0004 (0.0031)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0014 (0.0036)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">3B</td>
<td style="padding-left: 5px; padding-right: 5px">0.0040 (0.0027)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0071 (0.0031)<sup>*</sup></td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Loaded</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0024 (0.0029)</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0027 (0.0036)</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Outs</td>
<td style="padding-left: 5px; padding-right: 5px">-0.0036 (0.0006)<sup>***</sup></td>
<td style="padding-left: 5px; padding-right: 5px">-0.0043 (0.0006)<sup>***</sup></td>
</tr>
<tr class="odd" style="border-top: 1px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Num. obs.</td>
<td style="padding-left: 5px; padding-right: 5px">779106</td>
<td style="padding-left: 5px; padding-right: 5px">622199</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: BatterYear</td>
<td style="padding-left: 5px; padding-right: 5px">3578</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Num. groups: PitcherYear</td>
<td style="padding-left: 5px; padding-right: 5px">5424</td>
<td style="padding-left: 5px; padding-right: 5px">2876</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0256</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0011</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (full model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0142</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Adj. R<sup>2</sup> (proj model)</td>
<td style="padding-left: 5px; padding-right: 5px">0.0010</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">AIC</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">565917.2722</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">BIC</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">566087.3874</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Log Likelihood</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">-282943.6361</td>
</tr>
<tr class="odd">
<td style="padding-left: 5px; padding-right: 5px">Var: PitcherYear (Intercept)</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.0004</td>
</tr>
<tr class="even">
<td style="padding-left: 5px; padding-right: 5px">Var: PitcherYear × Next Batter xwOBA</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.0029</td>
</tr>
<tr class="odd" style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px; padding-right: 5px">Var: Residual</td>
<td style="padding-left: 5px; padding-right: 5px">&nbsp;</td>
<td style="padding-left: 5px; padding-right: 5px">0.1449</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="3" style="font-size: 0.8em">Standard errors in parentheses. *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05, . p &lt; 0.1</td>
</tr>
</tfoot>

</table>


<p>In both models, next_batter_xwOBA maintains a negative and statistically significant effect on the current batter’s expected outcome. Specifically, Model 1 estimates a coefficient of −0.0435 (SE=0.0177,p&lt;0.05), while Model 2, which allows for varying sensitivity across pitchers, estimates a slightly smaller effect of -0.0308 (SE=0.0133,p&lt;0.05). This consistency across model structures further reinforces the finding that stronger hitters on deck depress expected offensive performance in the current plate appearance.</p>
<p><strong>Takeaway:</strong> When we select for certain statistically significant fixed and random effects, we find that the next batter’s xwOBA continue to have a small but significant impact on the current plate appearance’s xwOBA, and this effect is negative. A stronger on-deck hitter results in lower than expected outcomes for that plate appearance.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>This study revisits the long-debated concept of lineup protection through the lens of modern expected statistics, large-scale data, and mixed-effects modeling. While sabermetric orthodoxy has long rejected the idea that the quality of the on-deck hitter meaningfully alters the current batter’s outcomes, our results challenge this narrative in subtle but important ways. Across several model formulations—including fixed effects, random slopes, and event-level decomposition—we consistently find that the quality of the next batter, as proxied by next_batter_xwOBA, has a small but statistically significant negative effect on the current plate appearance’s offensive value.</p>
<p>This effect—what we might term a “lineup penalty”—runs counter to the intuitive and anecdotal notion that strong protection behind a hitter will elevate their performance. Instead, we find that better on-deck hitters correlate with lower xwOBA and xBA for the current batter, suggesting that pitchers adjust their behavior not by avoiding the current batter, but by attacking them more aggressively and strategically. The breakdown of outcomes supports this: walks decline significantly when a stronger batter is on deck, while extra-base hits also become less likely. At the same time, the probability of in-play outs increases. These shifts point to a scenario where pitchers are throwing more hittable—but better located—pitches, reducing risk while suppressing offensive upside.</p>
<p>Although these effects are small in magnitude—a 0.0043 decrease in xwOBA or a ~0.003 decrease in xBA per 0.100 increase in next batter xwOBA—they are statistically robust and directionally consistent across all models tested. Moreover, the use of continuous next batter quality, rather than a binary “protected vs.&nbsp;unprotected” designation used in earlier studies, allows us to more precisely quantify variation and avoid confounding effects tied to lineup position or team-level strategy.</p>
<p>Our mixed-effects model with random slopes by pitcher-year reveals a further layer of nuance: not all pitchers respond to lineup protection in the same way. Some pitchers—like Tyler Glasnow and Paul Skenes—appear to suppress outcomes even more effectively when a strong hitter looms, possibly due to psychological edge, strategic discipline, or simply elite command. Others—like Roddery Muñoz or Martín Pérez—show the opposite pattern, struggling more in those same situations. These persistent individual differences open up a new frontier for pitcher evaluation: how well can a pitcher execute when the lineup context increases pressure? It’s not just about what stuff you throw—but how your performance responds to lineup dynamics.</p>
<p>From a team-building and analytics perspective, these findings carry several implications. First, they suggest that the identity of the on-deck hitter has measurable consequences for the batter at the plate, even if these effects are small on a per-plate appearance basis. Over the course of a season, these marginal effects can accumulate into meaningful differences in run expectancy and win probability. Second, simulation models and lineup optimization tools should not treat hitters as isolated agents, but as nodes in an interdependent sequence influenced by surrounding players. Finally, these results offer a framework to revisit and refine older lineup protection narratives, moving beyond anecdotes and toward quantifiable patterns.</p>
<p>Of course, there are limitations. While we’ve accounted for many confounders—game state, batter and pitcher quality, matchup handedness, and more—there remain unobserved variables that could shape pitcher strategy and hitter outcomes, including bullpen anticipation, fatigue, and scouting data not available in public Statcast feeds. We also focus on regular-season data, meaning our findings may differ in postseason or late-inning high-leverage contexts. Additionally, while we attempted to mitigate endogeneity concerns by using large samples and fixed effects, there is still potential for lineup construction biases (e.g., better hitters naturally hitting near each other) to influence results in ways we can’t fully untangle.</p>
<p>Nonetheless, the consistency of the negative relationship between next_batter_xwOBA and offensive outcomes—even after accounting for random slopes, outcome decomposition, and alternative model structures—suggests that lineup context does shape pitcher behavior in ways that reduce the expected success of the current batter. And crucially, these effects aren’t random—they’re stable, predictable, and player-specific.</p>
<p>In summary, this study demonstrates that lineup protection may exist, but not in the way it was originally imagined. It doesn’t make hitters more dangerous—it makes them more targeted. This turns the classic idea of protection on its head, raising the possibility that the best hitters don’t benefit from who’s behind them—but instead, must overcome the strategic adjustments their presence induces. Future work might explore how these effects differ by leverage, team philosophy, or pitch type, but for now, we can say with confidence: the batter on deck does matter. ## References</p>
<p>Ambrosino,&nbsp;D. (2011, November 30). <em>Orders of protection</em>. The Hardball Times. <a href="https://tht.fangraphs.com/orders-of-protection/" class="uri">https://tht.fangraphs.com/orders-of-protection/</a></p>
<p>Bradbury,&nbsp;J.&nbsp;C., &amp; Drinen,&nbsp;D.&nbsp;J. (2007). Pigou at the plate. <em>Journal of Sports Economics</em>, <em>9</em>(2), 211-224. <a href="https://doi.org/10.1177/1527002507300178" class="uri">https://doi.org/10.1177/1527002507300178</a></p>
<p>Britton,&nbsp;T. (2024, April 26). J.D. Martinez will be Pete Alonso’s protection in Mets lineup. Does that matter? <em>The New York Times</em>. <a href="https://www.nytimes.com/athletic/5443604/2024/04/26/mets-pete-alonso-jd-martinez-lineup/" class="uri">https://www.nytimes.com/athletic/5443604/2024/04/26/mets-pete-alonso-jd-martinez-lineup/</a></p>
<p>Cameron,&nbsp;D. (2012, May 25). <em>Cameron: McCutchen disproves lineup protection</em>. ESPN.com. <a href="https://insider.espn.com/mlb/insider/story/_/id/7970598/andrew-mccutchen-another-example-why-lineup-protection-myth-mlb" class="uri">https://insider.espn.com/mlb/insider/story/_/id/7970598/andrew-mccutchen-another-example-why-lineup-protection-myth-mlb</a></p>
<p>How to quantify lineup protection in baseball — The Paraball notes. (2024, April 9). <em>The Paraball Notes</em>. <a href="https://www.paraballnotes.com/blog/how-to-quantify-lineup-protection-in-baseball" class="uri">https://www.paraballnotes.com/blog/how-to-quantify-lineup-protection-in-baseball</a></p>
<p>Laurila,&nbsp;D. (2016, July 14). <em>Player’s view: Does lineup protection exist?</em> FanGraphs Baseball. <a href="https://blogs.fangraphs.com/players-view-does-lineup-protection-exist/" class="uri">https://blogs.fangraphs.com/players-view-does-lineup-protection-exist/</a></p>
<p>Petriello,&nbsp;M. (2015, April 13). <em>Billy Hamilton’s reverse lineup protection</em>. FanGraphs Baseball. <a href="https://blogs.fangraphs.com/billy-hamiltons-reverse-lineup-protection/" class="uri">https://blogs.fangraphs.com/billy-hamiltons-reverse-lineup-protection/</a></p>
<p>Phillips,&nbsp;D.&nbsp;C. (2011). You’re hurting my game: Lineup protection and injuries in Major League Baseball. <em>Journal of Quantitative Analysis in Sports</em>, <em>7</em>(3). <a href="https://doi.org/10.2202/1559-0410.1296" class="uri">https://doi.org/10.2202/1559-0410.1296</a></p>
<p>Stavenhagen,&nbsp;C. (2019, May 7). The (latest) numbers behind Miguel Cabrera’s remarks on lineup protection. <em>The New York Times</em>. <a href="https://www.nytimes.com/athletic/965467/2019/05/07/the-latest-numbers-behind-miguel-cabreras-remarks-on-lineup-protection/" class="uri">https://www.nytimes.com/athletic/965467/2019/05/07/the-latest-numbers-behind-miguel-cabreras-remarks-on-lineup-protection/</a></p>
<p>Tango,&nbsp;T. (2006, April 7). <em>Pitching around batters</em>. The Hardball Times. <a href="https://tht.fangraphs.com/pitching-around-batters/" class="uri">https://tht.fangraphs.com/pitching-around-batters/</a></p>
<p>Weinberg,&nbsp;N. (2013, January 1). <em>Lineup protection: Fact or fiction?</em> New English D. <a href="https://newenglishd.com/2013/01/01/lineup-protection-fact-or-fiction/" class="uri">https://newenglishd.com/2013/01/01/lineup-protection-fact-or-fiction/</a></p>
<p>Wiser,&nbsp;J. (2014, February 19). <em>Let’s talk about lineup protection</em>. Inside the ’Zona. <a href="https://insidethezona.com/2014/02/lets-talk-lineup-protection/" class="uri">https://insidethezona.com/2014/02/lets-talk-lineup-protection/</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025. All rights reserved.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>