{
  "hash": "b27685eb8d4ae2134c30990e2f0bad99",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Blog Post #2: Swing Profiles\"\nauthor: \"Lance Brady\"\ndate: \"2025-02-26\"\ncategories: [swing profiles, lineups, statcast]\nformat: html\neditor: visual\nimage: blog2.jpg\n---\n\n\n\n## Introduction to Swing Profile Data\n\nRecent advances in Statcast technology have allowed for the direct measurement of bat speed and swing length on pitches where the batter swings. These new metrics open the door to exploring questions that were previously left to inference, scouting reports, or assumptions about mechanics. Specifically, we have become interested in the idea of swing consistency: How much do a batter’s bat speed and swing length deviate from pitch to pitch or from game to game? How do differing swing profiles on a roster correlate with run generation during a game?\n\nThis article addresses three connected but distinct angles on these new metrics:\n\n**Individual-Level Swing Diversity:** Do stable or volatile swing metrics for a single batter over a season correlate with that batter’s offensive success, measured through wOBA or xwOBA?\n\n**Game-Level Team Swing Diversity:** Does a club whose hitters share similar or very different swing metrics on a given day see any advantage in that day’s run production?\n\nOur analysis aims not to prove a direct cause-and-effect relationship but rather to uncover whether correlations exist that might guide roster construction, daily lineup decisions, or player development. Given that these bat speed and swing length metrics are new, we expect some initial findings to be exploratory, setting the stage for deeper or more controlled studies in the future.\n\n**Fundamental Questions Of Our Study**\n\n1.  **Individual**: Is consistency associated with higher personal performance once I factor out average skill?\n\n2.  **Game**: On a day-to-day basis, does having a consistent or varied approach correlate with daily offensive output?\n\n## Methods\n\nFirst, we loaded in our libraries and read the data, which contains almost every pitch from the 2024 season (excluding when poor data was retrieved).\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# url included if we wanted to use read_csv with this data from an AWS S3 bucket\n# statcast_url = \"https://lances-lineups-data.s3.us-east-2.amazonaws.com/statcast_data.csv\"\nstatcast_data <- read.csv(\"data/statcast_data.csv\")\n```\n:::\n\n\n\n### Question I: Does having a variety of average swing characteristics across players on the roster help or hurt scoring?\n\n#### Question IA: Does Variation in Swing Length or Swing Speed individually help a Team across a season?\n\nWe will want to create a weighted standard deviation-like metric for a team's between-player swing style, either swing length or swing speed, variation. This will essentially be a weighted standard deviation of a team's player's average swing style for those two variables. I decide to give weight to each player by Plate Appearances, not by number of swings. This is because for a particular team, we do not want to overweight the free-swinging players just because they have more swing data. We want to consider player-team combinations, so that a player's plate appearances for a certain team are treated separately from their plate appearances for another team, if they played for multiple teams in this season for some reason. This will account for the fact that a player might change swing characteristics upon getting to a new team.\n\nFirst, let's create a unique ID for each Plate Appearance in `pitches`.\n\nFor each at-bat, decide if the batter is on the `home_team` (if `inning_topbot` == \"Bot\") or the `away_team` (if `inning_topbot` == \"Top\"). This assignment handles trades automatically, because the data for each game has the correct home/away teams for that date.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npitches <- statcast_data %>%\n  mutate(\n    PA_id = paste(game_pk, at_bat_number, sep=\"_\"),\n    batter_team = ifelse(inning_topbot == \"Bot\", home_team, away_team)\n  )\n```\n:::\n\n\n\nAt this point, a single batter can have multiple rows with different batter_team values if they switched teams mid-season. Each row corresponds to a single plate appearance.\n\nNow we define each combination (batter, batter_team) separately, so we only include that player’s PAs while on that team.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Each (batter, batter_team) combination with total PAs\nbatter_team_pa_count <- pitches %>%\n  group_by(batter, batter_team) %>%\n  distinct(PA_id) %>%\n  summarise(total_PA_for_that_team = n(), .groups=\"drop\") %>%\n  arrange(batter, batter_team)\n```\n:::\n\n\n\nChecking players who switched teams midway through, like Justin Turner, who had 349 PAs for Toronto along with 190 PAs for Seattle, we can see that the `batter_team_pa_count` is about correct. We get 332 and 189 PAs in our data respectively, likely due to some missing data.\n\nTo get mean swing length for a player, we need to use only the rows from the times the batter was on that team. That means merging in batter_team_map so we can group by (batter, batter_team).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbatter_team_swing_stats <- pitches %>%\n  # Keep rows where swing_length and bat_speed are not NA\n  filter(!is.na(swing_length), !is.na(bat_speed)) %>%\n  group_by(batter, batter_team) %>%\n  summarise(\n    mean_swing_length = mean(swing_length, na.rm=TRUE),\n    mean_bat_speed = mean(bat_speed, na.rm=TRUE), # Will need in Question IB\n    sd_swing_length = sd(swing_length, na.rm=TRUE), # Will need later\n    sd_bat_speed = sd(bat_speed, na.rm=TRUE), # Will need later\n    .groups=\"drop\"\n  )\n```\n:::\n\n\n\nFor each batter-team combination, we now have the mean swing length and bat speed, along with standard deviation. We can now calculate the weighted standard deviation of swing length for each team.\n\nWe want to first add the total PA for each batter-team combination to the `batter_team_swing_stats` data frame. This will allow us to weight the standard deviation of swing length by the number of plate appearances for each player.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbatter_team_swing_stats <- batter_team_swing_stats %>%\n  left_join(batter_team_pa_count, by=c(\"batter\", \"batter_team\"))\n```\n:::\n\n\n\nWe’ll define a small helper to compute weighted SD:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweighted_sd <- function(x, w) {\n  w_mean <- sum(x * w, na.rm=TRUE) / sum(w, na.rm=TRUE)\n  w_var  <- sum(w * (x - w_mean)^2, na.rm=TRUE) / sum(w, na.rm=TRUE)\n  sqrt(w_var)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nteam_diversity <- batter_team_swing_stats %>%\n  group_by(batter_team) %>%\n  summarise(\n    # Weighted SD of each player's mean bat_speed\n    team_sd_mean_bat_speed = weighted_sd(mean_bat_speed, total_PA_for_that_team),\n    # Weighted SD of each player's mean swing_length\n    team_sd_mean_swing_length = weighted_sd(mean_swing_length, total_PA_for_that_team),\n    .groups=\"drop\"\n  )\n```\n:::\n\n\n\nWe now have the weighted standard deviation of swing length for each team. We can now check if this variation in swing length helps or hurts scoring. We will use wOBA and xWOBA as proxies for scoring. We will do these calculations manually as our dataset does not include all 2024 Plate Appearances so we will only focus on our subset of the data. We will use the `woba_value` and `woba_denom` column in `pitches` to calculate wOBA for each plate appearance. We will then calculate the average wOBA for each team.\n\nTypically, wOBA is credited once per completed PA (plate appearance). In many Statcast datasets, woba_value and woba_denom are only non-zero on the final pitch of the PA. However, to ensure we only count each PA once, we can explicitly slice the final pitch of each (game_pk, at_bat_number).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We'll define \"final pitch\" as the last pitch_number in that (game_pk, at_bat_number)\nfinal_pitches <- pitches %>%\n  group_by(game_pk, at_bat_number) %>%\n  slice_max(order_by = pitch_number, n = 1) %>%\n  ungroup()\n```\n:::\n\n\n\nNow final_pitches has exactly 1 row per completed PA. This is our formula for wOBA:\n\nUpon inspecting the data, we can see that there are some rows for which `woba_value` or `woba_denom` are NA, so we will filter those out.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_pitches_clean <- final_pitches %>%\n  filter(!is.na(woba_denom), !is.na(woba_value))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nteam_woba <- final_pitches_clean %>%\n  group_by(batter_team) %>%\n  summarise(\n    total_woba_value = sum(woba_value, na.rm=TRUE),\n    total_woba_denom = sum(woba_denom, na.rm=TRUE),\n    team_wOBA = ifelse(total_woba_denom == 0, NA,\n                       total_woba_value / total_woba_denom),\n    .groups=\"drop\"\n  ) %>%\n  select(-total_woba_value, -total_woba_denom) %>%\n  arrange(desc(team_wOBA))\n```\n:::\n\n\n\nThis list seems to make sense and is in line with overall 2024 data. Typically, woba_denom is 1 for outcomes like walks, hit-by-pitch, or batted-ball events. For sacrifice flies or other rare events, it can vary slightly. The sum of woba_denom for a team is essentially the sum of PAs used in the wOBA formula (excluding some events like catcher interference or maybe intentionals, depending on how MLBAM codes them). So, its sum is essentially \"the count of wOBA-relevant plate appearances\".\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_df <- team_diversity %>%\n  left_join(team_woba,  by=\"batter_team\")\n```\n:::\n\n\n\nWe can also calculate xwOBA for each team. xwOBA is a more advanced metric that uses exit velocity and launch angle to estimate the expected wOBA for each batted ball. We will use the `estimated_woba_using_speedangle` column in `pitches` to calculate xwOBA for each batted-ball plate appearance, then account for walks, hit-by-pitches, etc. We will then calculate the average xwOBA for each team.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_pitches_xwoba <- final_pitches %>%\n  filter(!is.na(estimated_woba_using_speedangle)) %>%\n  mutate(\n    xWOBA_value = estimated_woba_using_speedangle,\n    xWOBA_denom = 1\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nteam_xwoba <- final_pitches_xwoba %>%\n  group_by(batter_team) %>%\n  summarise(\n    total_xwoba_value = sum(xWOBA_value, na.rm=TRUE),\n    total_xwoba_denom = sum(xWOBA_denom, na.rm=TRUE),\n    team_xwOBA = ifelse(total_xwoba_denom == 0, NA,\n                        total_xwoba_value / total_xwoba_denom),\n    .groups=\"drop\"\n  ) %>%\n  select(-total_xwoba_value, -total_xwoba_denom) %>%\n  arrange(desc(team_xwOBA))\n```\n:::\n\n\n\nThis also seems to make sense and is in line with overall 2024 data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_df <- analysis_df %>%\n  left_join(team_xwoba, by=\"batter_team\")\n```\n:::\n\n\n\n#### Bat Speed\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(analysis_df, aes(x=team_sd_mean_bat_speed, y=team_wOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Speed Diversity vs. Team wOBA\",\n    x=\"Team SD of Mean Bat Speed\",\n    y=\"Team wOBA\"\n  )+\n  theme_pub()+\n  ## Add trendline\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nLet's create a linear model to see if there is a significant relationship between team swing speed diversity and team wOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_woba <- lm(team_wOBA ~ team_sd_mean_bat_speed, data=analysis_df)\nsummary(lm_woba)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_wOBA ~ team_sd_mean_bat_speed, data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.037205 -0.007888 -0.001217  0.010741  0.024043 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            0.305091   0.015363  19.859   <2e-16 ***\nteam_sd_mean_bat_speed 0.005201   0.005375   0.968    0.341    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01376 on 28 degrees of freedom\nMultiple R-squared:  0.03236,\tAdjusted R-squared:  -0.002197 \nF-statistic: 0.9364 on 1 and 28 DF,  p-value: 0.3415\n```\n\n\n:::\n:::\n\n\n\nIn this linear model, we get a negative Adjusted R-squared, signalling that there’s almost no linear relationship—in other words, once the penalty for adding a predictor is applied, the model explains less variance than just using the mean. The p-value is 0.341, which is insignificant at the 0.05 level. This suggests that there is no significant relationship between team swing speed diversity and team wOBA.\n\nLet's also check the relationship between team swing speed diversity and team xwOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(analysis_df, aes(x=team_sd_mean_bat_speed, y=team_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Speed Diversity vs. Team xwOBA\",\n    x=\"Team SD of Mean Bat Speed\",\n    y=\"Team xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_xwoba <- lm(team_xwOBA ~ team_sd_mean_bat_speed, data=analysis_df)\nsummary(lm_xwoba)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_xwOBA ~ team_sd_mean_bat_speed, data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.028354 -0.008561 -0.002876  0.008982  0.025606 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            0.290644   0.014814  19.619   <2e-16 ***\nteam_sd_mean_bat_speed 0.007635   0.005183   1.473    0.152    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01327 on 28 degrees of freedom\nMultiple R-squared:  0.07193,\tAdjusted R-squared:  0.03879 \nF-statistic:  2.17 on 1 and 28 DF,  p-value: 0.1519\n```\n\n\n:::\n:::\n\n\n\nThe Adjusted R-Squared for this model is positive, and the p-value of team-level bat speed diversity has gone down to 0.177. It is possible that with more data from other seasons, we would be able to see more signficiant relationships between team-level bat speed diversity and team xwOBA.\n\nHowever, at this point, it is worth noting that our data is pointing to the possibility of a relationship, even if it is small, between team-level bat speed diversity and team xwOBA. This is worth more exploration.\n\nLet's do the same for swing length.\n\n#### Swing Length\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(analysis_df, aes(x=team_sd_mean_swing_length, y=team_wOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Length Diversity vs. Team wOBA\",\n    x=\"Team SD of Mean Swing Length\",\n    y=\"Team wOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_woba <- lm(team_wOBA ~ team_sd_mean_swing_length, data=analysis_df)\nsummary(lm_woba)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_wOBA ~ team_sd_mean_swing_length, data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.036636 -0.008650 -0.002102  0.011271  0.024778 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               0.317075   0.012163  26.068   <2e-16 ***\nteam_sd_mean_swing_length 0.006875   0.030472   0.226    0.823    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01398 on 28 degrees of freedom\nMultiple R-squared:  0.001814,\tAdjusted R-squared:  -0.03384 \nF-statistic: 0.0509 on 1 and 28 DF,  p-value: 0.8231\n```\n\n\n:::\n:::\n\n\n\nThe Adjusted R-squared for swing length is also negative, and the p-value is 0.823, which is insignificant at the 0.05 level. This suggests that there is no significant relationship between team swing length diversity and team wOBA.\n\nLet's also check the relationship between team swing length diversity and team xwOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(analysis_df, aes(x=team_sd_mean_swing_length, y=team_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Length Diversity vs. Team xwOBA\",\n    x=\"Team SD of Mean Swing Length\",\n    y=\"Team xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_xwoba <- lm(team_xwOBA ~ team_sd_mean_swing_length, data=analysis_df)\nsummary(lm_xwoba)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_xwOBA ~ team_sd_mean_swing_length, data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.028497 -0.009080 -0.002055  0.011655  0.028380 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                0.30086    0.01179  25.526   <2e-16 ***\nteam_sd_mean_swing_length  0.02899    0.02953   0.982    0.335    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01354 on 28 degrees of freedom\nMultiple R-squared:  0.03329,\tAdjusted R-squared:  -0.001233 \nF-statistic: 0.9643 on 1 and 28 DF,  p-value: 0.3345\n```\n\n\n:::\n:::\n\n\n\nAgain, our Adjusted R-Squared is negative, and the p-value of the team-level swing length diversity is 0.367. This suggests that there is no significant relationship between team swing length diversity and team xwOBA.\n\nIn conclusion, we have found that there is no significant relationship between team swing length diversity and team wOBA or xwOBA. This suggests that having a variety of average swing length characteristics across players on the roster does not help or hurt scoring.\n\nIt is worth noting that our xwOBA data seems to point towards stronger relationships than our wOBA data. In theory, xwOBA is a more trustworthy measure of offensive production, because it looks to eliminate the noise of defense and luck. Sometimes including both together—or creating a combined 2D measure—can reveal patterns not evident in either metric separately.\n\nPerhaps the simplest approach is to include both predictors in the same linear model as a multiple regression model.\n\n### Multivariate Approach of Swing \"Style\"\n\n#### Multiple Regression Model\n\nIf `team_sd_mean_swing_length` was “useless” by itself, it could still contribute additional explanatory power in the presence of `team_sd_mean_bat_speed`. For example, maybe a team with both high bat‐speed diversity and high swing‐length diversity has synergy (or a deficiency).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using wOBA\nmod_multi <- lm(team_wOBA ~ team_sd_mean_bat_speed + team_sd_mean_swing_length,\n                data = analysis_df)\nsummary(mod_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_wOBA ~ team_sd_mean_bat_speed + team_sd_mean_swing_length, \n    data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.036697 -0.008451 -0.001479  0.010265  0.024673 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                0.306548   0.015998  19.161   <2e-16 ***\nteam_sd_mean_bat_speed     0.006809   0.006726   1.012    0.320    \nteam_sd_mean_swing_length -0.015350   0.037546  -0.409    0.686    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01397 on 27 degrees of freedom\nMultiple R-squared:  0.03832,\tAdjusted R-squared:  -0.03292 \nF-statistic: 0.5379 on 2 and 27 DF,  p-value: 0.5901\n```\n\n\n:::\n\n```{.r .cell-code}\n# Using xWOBA\nmod_multi <- lm(team_xwOBA ~ team_sd_mean_bat_speed + team_sd_mean_swing_length,\n                data = analysis_df)\nsummary(mod_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = team_xwOBA ~ team_sd_mean_bat_speed + team_sd_mean_swing_length, \n    data = analysis_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.028559 -0.008475 -0.003035  0.009484  0.025352 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               0.290056   0.015467  18.754   <2e-16 ***\nteam_sd_mean_bat_speed    0.006987   0.006503   1.074    0.292    \nteam_sd_mean_swing_length 0.006191   0.036297   0.171    0.866    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01351 on 27 degrees of freedom\nMultiple R-squared:  0.07293,\tAdjusted R-squared:  0.004259 \nF-statistic: 1.062 on 2 and 27 DF,  p-value: 0.3598\n```\n\n\n:::\n:::\n\n\n\nThe Adjusted R-Squared for both models are negative, suggesting that while team-level bat speed variation may help explain between-team variation in xWOBA, a combined model with swing length is not providing any explanation for the variation in xWOBA or wOBA. In both models, the p-values for both predictors are also insignificant at the 0.05 level.\n\nIt is worth noting that other models with interaction and transformed predictors were considered, though nothing yielded a realistic and suitable result.\n\nGiven that all of this data analysis was done on 30 data points (30 teams), we would like to consider a team's wOBA and xWOBA for each game.\n\nTakeaway #1: Having a variety of swing speeds on a roster could correlate with expected scoring statistics for a team over a season, but a variety of swing lengths does not.\n\n### Question IB: Within a game, does consistency of a team's swings help or hurt scoring?\n\nIn this model, we can incorporate situational or day‐to‐day changes in the team’s lineup (maybe a star was resting, or they traded for a new hitter mid‐season). We will want to compute each team’s in‐game diversity of swing speed and swing length weighted by plate appearances, then comparing that to the team’s in‐game wOBA and xwOBA.\n\nFirst, we group by (game_pk, batter_team, batter) to compute the mean and median for each player in that game. We also count how many plate appearances that batter had in that game.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npitches = read.csv(\"data/statcast_data.csv\")\n\npitches <- pitches %>%\n  mutate(\n    PA_id = paste(game_pk, at_bat_number, sep=\"_\"),\n    batter_team = ifelse(inning_topbot == \"Bot\", home_team, away_team)\n  )\n\nplayer_game_allPA <- pitches %>%\n  group_by(game_pk, batter, batter_team) %>%\n  summarise(\n    total_pa_game = n_distinct(PA_id),    # all PAs in that game for that batter\n    .groups = \"drop\"\n  )\n\n# Subset to actual swings\nbatter_game_swings <- pitches %>%\n  filter(!is.na(bat_speed), !is.na(swing_length)) %>%\n  group_by(game_pk, batter, batter_team) %>%\n  summarise(\n    # mean & median for the swings that occurred\n    game_median_bat_speed    = median(bat_speed, na.rm=TRUE),\n    game_median_swing_length = median(swing_length, na.rm=TRUE),\n    .groups=\"drop\"\n  )\n```\n:::\n\n\n\nFinally, we do a left_join so that every (game, batter, team) from player_game_allPA is preserved—even if the player never swung:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbatter_game_stats <- player_game_allPA %>%\n  left_join(batter_game_swings,\n            by = c(\"game_pk\", \"batter\", \"batter_team\"))\n```\n:::\n\n\n\nSome batters (especially if they only had one PA) might have 0 swings and thus NA data for the swing columns. That is okay, as they will not effect our weighted standard deviations.\n\nNow, let's get our team-level game-by-game diversity of swing speed and swing length. We will use the same weighted standard deviation formula as before, but this time we will use the game_mean_bat_speed and game_mean_swing_length columns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteam_game_diversity <- batter_game_stats %>%\n  group_by(game_pk, batter_team) %>%\n  summarise(\n    # Weighted SD of each player's median (bat_speed)\n    game_sd_median_bat_speed = weighted_sd(game_median_bat_speed, total_pa_game),\n\n    # Weighted SD of each player's median (swing_length)\n    game_sd_median_swing_length = weighted_sd(game_median_swing_length, total_pa_game),\n    \n    .groups = \"drop\"\n  )\n```\n:::\n\n\n\nNow each row in team_game_diversity is a single (game_pk, batter_team) with four different “diversity” metrics (two based on mean, two based on median).\n\nNext, we will compute game-level xWOBA and wOBA for each team. We will use the same formula as before, but this time we will use the `woba_value` and `woba_denom` columns in `pitches` to calculate wOBA for each plate appearance. We will then calculate the average wOBA for each team.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngame_woba <- final_pitches_clean %>%\n  group_by(game_pk, batter_team) %>%\n  summarise(\n    total_woba_val   = sum(woba_value, na.rm=TRUE),\n    total_woba_denom = sum(woba_denom, na.rm=TRUE),\n    game_wOBA = ifelse(total_woba_denom == 0, NA,\n                       total_woba_val / total_woba_denom),\n    .groups=\"drop\"\n  ) %>%\n  select(game_pk, batter_team, game_wOBA)\n\ngame_xwoba <- final_pitches_xwoba %>%\n  group_by(game_pk, batter_team) %>%\n  summarise(\n    total_xwoba_value   = sum(xWOBA_value, na.rm=TRUE),\n    total_xwoba_denom = sum(xWOBA_denom, na.rm=TRUE),\n    game_xwOBA = ifelse(total_xwoba_denom == 0, NA,\n                        total_xwoba_value / total_xwoba_denom),\n    .groups=\"drop\"\n  ) %>%\n  select(game_pk, batter_team, game_xwOBA)\n```\n:::\n\n\n\nNow, combine into an analysis dataframe:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_game_df <- team_game_diversity %>%\n  left_join(game_woba, by=c(\"game_pk\", \"batter_team\"))\n\nanalysis_game_df <- analysis_game_df %>%\n  left_join(game_xwoba, by=c(\"game_pk\",\"batter_team\"))\n```\n:::\n\n\n\nLet's make our models for swing length:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Median-based statistics\nmedian_woba_swing_length_model <- lm(game_wOBA ~ game_sd_median_swing_length,\n                    data=analysis_game_df)\nsummary(median_woba_swing_length_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = game_wOBA ~ game_sd_median_swing_length, data = analysis_game_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.280789 -0.061869 -0.002215  0.062242  0.311536 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  0.331454   0.004442  74.610  < 2e-16 ***\ngame_sd_median_swing_length -0.035054   0.008007  -4.378 1.22e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0898 on 4804 degrees of freedom\nMultiple R-squared:  0.003973,\tAdjusted R-squared:  0.003766 \nF-statistic: 19.16 on 1 and 4804 DF,  p-value: 1.225e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian_xwoba_swing_length_model <- lm(game_xwOBA ~ game_sd_median_swing_length,\n                    data=analysis_game_df)\nsummary(median_xwoba_swing_length_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = game_xwOBA ~ game_sd_median_swing_length, data = analysis_game_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.240329 -0.046413 -0.002318  0.044446  0.235543 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  0.320361   0.003298   97.13  < 2e-16 ***\ngame_sd_median_swing_length -0.022292   0.005945   -3.75 0.000179 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06667 on 4804 degrees of freedom\nMultiple R-squared:  0.002918,\tAdjusted R-squared:  0.002711 \nF-statistic: 14.06 on 1 and 4804 DF,  p-value: 0.0001792\n```\n\n\n:::\n:::\n\n\n\nWe tried out both mean and median-based models to ensure that outliers in the data were not influencing individual player's swing data. However, the mean-based and median-based models are showing similar results. Thus, we are going to graph just median-based results, as they are much more signficiant. These four models are all interesting though, with significant p-values for all coefficients of team swing length diversity, and positive Adjusted R-Squared values, even if incredibly small, for all models.\n\nThe coefficients for team swing length diversity are all negative, suggesting that on a game-by-game basis, a more consistent swing length is correlated with better offensive production. The p-values are all significant at the 0.05 level, suggesting that there is a significant relationship between team swing length diversity and team wOBA and xwOBA. The Adjusted R-Squared values are all positive, suggesting that the models explain some variance in team wOBA and xwOBA.\n\nThis finding is interesting, as it could point to a number of things: - Consistent team-wide swing length approaches might be best for scoring - Our team-by-team data might simply have not had enough sample size to find significant correlations\n\nOne possible explanation: The teams with the best scouting and analytics can prepare their players similarly for a particular game, allowing them to capitalize on the opponents' weaknesses or particular ballpark-related advantages.\n\nLet's make our models for bat speed:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Median-based statistics\nmedian_woba_bat_speed_model <- lm(game_wOBA ~ game_sd_median_bat_speed,\n                    data=analysis_game_df)\nsummary(median_woba_bat_speed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = game_wOBA ~ game_sd_median_bat_speed, data = analysis_game_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.280950 -0.062190 -0.001972  0.062406  0.311361 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               0.316606   0.003393  93.312   <2e-16 ***\ngame_sd_median_bat_speed -0.001043   0.000871  -1.198    0.231    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.08997 on 4804 degrees of freedom\nMultiple R-squared:  0.0002985,\tAdjusted R-squared:  9.044e-05 \nF-statistic: 1.435 on 1 and 4804 DF,  p-value: 0.2311\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian_xwoba_bat_speed_model <- lm(game_xwOBA ~ game_sd_median_bat_speed,\n                    data=analysis_game_df)\nsummary(median_xwoba_bat_speed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = game_xwOBA ~ game_sd_median_bat_speed, data = analysis_game_df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.237892 -0.046046 -0.002679  0.044713  0.232560 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.082e-01  2.518e-03 122.407   <2e-16 ***\ngame_sd_median_bat_speed 8.167e-05  6.465e-04   0.126    0.899    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06677 on 4804 degrees of freedom\nMultiple R-squared:  3.323e-06,\tAdjusted R-squared:  -0.0002048 \nF-statistic: 0.01596 on 1 and 4804 DF,  p-value: 0.8995\n```\n\n\n:::\n:::\n\n\n\nIn all models except 1, we got both a negative Adjusted R-Squared and an insignifcant sign of the coefficient. In our model of game-level team bat speed diversity with wOBA, we got a positive Adjusted R-Squared, but the p-value of the coefficient is insignificant at the 0.05 level, and it does not line up with the model using xWOBA, and thus, I will ignore it as likely due to random chance. This suggests that on a game-by-game basis, consistency in a team's bat speed does not correlate positively or negatively with increased scoring.\n\nThis inversion from our potential correlations in team-level bat speed diversity and team xwOBA is interesting.\n\nOne possible explanation: Throughout a season, a team that has a variety of bat speeds can more easily adapt to the many pitchers they face. In one particular game, a team's variety of bat speeds does not prove useful when they may only face two or three pitchers, provided that the starter pitches for a large portion of the game.\n\nLet's graph these scenarios, using the median variation values and xWOBA:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(analysis_game_df, aes(x=game_sd_median_swing_length, y=game_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Length Diversity vs. Team xwOBA\",\n    x=\"Game SD of Median Swing Length\",\n    y=\"Game xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(analysis_game_df, aes(x=game_sd_median_bat_speed, y=game_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Team Swing Speed Diversity vs. Team xwOBA\",\n    x=\"Game SD of Median Bat Speed\",\n    y=\"Game xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-2.png){width=672}\n:::\n:::\n\n\n\nTakeaway #2: On a game-by-game basis, a team's swing length consistency is correlated with better offensive production, while a team's bat speed consistency is not.\n\nThinking about Takeaways 1 and 2 together, it is possible that a team's swing length consistency in a particular game points to the idea that they have prepared for a particular set of pitchers well and are able to achieve similar swing lengths to best capitalize on the attributes of the opposing pitchers or of the ballpark. However, over an entire season, it could be advantageous to have a variety of swing speeds on a roster to be able to attack the wide variety of pitchers faced, while optimal swing lengths average out over a long season and many pitchers. It is possible that swing lengths are easier to fluctuate on a per-game basis, but swing speeds are more difficult to change, thus a variety is needed on a roster.\n\n#### Multivariate Model\n\nLet's also try one multivariate model to see if we can find a relationship between swing style consistency and xwOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_multi <- lm(game_xwOBA ~ game_sd_median_bat_speed + game_sd_median_swing_length,\n                data = analysis_game_df)\nsummary(mod_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = game_xwOBA ~ game_sd_median_bat_speed + game_sd_median_swing_length, \n    data = analysis_game_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.23922 -0.04616 -0.00230  0.04443  0.23585 \n\nCoefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  0.3186182  0.0033550  94.969  < 2e-16 ***\ngame_sd_median_bat_speed     0.0021913  0.0007875   2.783  0.00541 ** \ngame_sd_median_swing_length -0.0338689  0.0072529  -4.670  3.1e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06663 on 4803 degrees of freedom\nMultiple R-squared:  0.004523,\tAdjusted R-squared:  0.004108 \nF-statistic: 10.91 on 2 and 4803 DF,  p-value: 1.871e-05\n```\n\n\n:::\n:::\n\n\n\nIn this model, both bat speed and swing length are significant at the 0.05 level, and the Adjusted R-Squared is positive. This suggests that there is a significant relationship between team swing length and bat speed consistency and team xwOBA on a game-by-game basis.\n\nThis suggests that, holding swing length diversity constant, having a range of bat speeds within the lineup may help on a game-by-game basis. It could allow the team to adapt to differing pitch velocities and styles from the opposing pitchers.\n\nMeanwhile, holding bat speed diversity constant, a more consistent (less diverse) swing length appears beneficial. If everyone’s length is dialed in for that day’s pitcher(s), the team might more efficiently square up pitches or stay in the optimal “contact window.”\n\nOn a single‐game basis, these results indicate that a consistent swing length is linked to better offensive output, while some diversity in bat speed can be helpful. This aligns with the idea that hitters can unify their swing lengths to match that day’s pitchers and still bring different swing speeds to handle velocity changes or relief pitchers.\n\nOne possible explanation: For a particular game, a team's swing length helps them better adjust for ballpark dimensions or aspects of the weather/environment, but a team's bat speed diversity helps them adjust to the variety of pitchers they face.\n\n### Question II: Does a player's swing consistency help or hurt scoring?\n\nNow, we'd like to ask whether on a player-by-player basis, does a player's swing consistency during a season correlate with success at the plate? We will use the same weighted standard deviation formula as before, but this time we will use the player's mean swing length and bat speed for the season. Asked another way: Does having a consistent swing over a season correlate with a particular player generating offense.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npitches <- pitches %>%\n  mutate(\n    PA_id = paste(game_pk, at_bat_number, sep=\"_\"),\n    batter_team = ifelse(inning_topbot == \"Bot\", home_team, away_team)\n  )\n\nplayer_swing_consistency <- pitches %>%\n  filter(!is.na(swing_length), !is.na(bat_speed)) %>%\n  group_by(batter) %>%\n  summarise(\n    # Season-long means\n    mean_swing_length = mean(swing_length, na.rm=TRUE),\n    mean_bat_speed    = mean(bat_speed, na.rm=TRUE),\n    # Season-long standard deviations\n    sd_swing_length = sd(swing_length, na.rm=TRUE),\n    sd_bat_speed    = sd(bat_speed, na.rm=TRUE),\n    .groups = \"drop\"\n  )\n\n## Take out players with NA standard deviation\nplayer_swing_consistency <- player_swing_consistency %>%\n  filter(!is.na(sd_swing_length), !is.na(sd_bat_speed))\n```\n:::\n\n\n\nThis gives us one row per batter, capturing that player’s overall pitch-to-pitch variation in swing metrics across the entire season.\n\nNow, let's calculate xWOBA for all players over the season.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We'll define \"final pitch\" as the last pitch_number in that (game_pk, at_bat_number)\nfinal_pitches <- pitches %>%\n  group_by(game_pk, at_bat_number) %>%\n  slice_max(order_by = pitch_number, n = 1) %>%\n  ungroup()\n\nfinal_pitches_xwoba <- final_pitches %>%\n  filter(!is.na(estimated_woba_using_speedangle)) %>%\n  mutate(\n    xWOBA_value = estimated_woba_using_speedangle,\n    xWOBA_denom = 1\n  )\n\nplayer_xwoba <- final_pitches_xwoba %>%\n  group_by(batter) %>%\n  summarise(\n    total_xwoba_value = sum(xWOBA_value, na.rm=TRUE),\n    total_xwoba_denom = sum(xWOBA_denom, na.rm=TRUE),\n    player_xwOBA = ifelse(total_xwoba_denom == 0, NA,\n                          total_xwoba_value / total_xwoba_denom),\n    .groups=\"drop\"\n  ) %>%\n  select(batter, player_xwOBA)\n```\n:::\n\n\n\nNow, combine into an analysis dataframe:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplayer_analysis_df <- player_swing_consistency %>%\n  left_join(player_xwoba, by=\"batter\")\n```\n:::\n\n\n\nLet's graph these scenarios, using the median variation values and xWOBA:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(player_analysis_df, aes(x=sd_swing_length, y=player_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Player Swing Length Consistency vs. Player xwOBA\",\n    x=\"Player SD of Swing Length\",\n    y=\"Player xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(player_analysis_df, aes(x=sd_bat_speed, y=player_xwOBA)) +\n  geom_point() +\n  labs(\n    title=\"Player Bat Speed Consistency vs. Player xwOBA\",\n    x=\"Player SD of Bat Speed\",\n    y=\"Player xwOBA\"\n  )+\n  theme_pub()+\n  geom_smooth(method=\"lm\", se=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-37-2.png){width=672}\n:::\n:::\n\n\n\nLet's also create linear models to see if there is a significant relationship between player swing consistency and player xwOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_sd_swing_length <- lm(player_xwOBA ~ mean_swing_length + sd_swing_length, data=player_analysis_df)\nsummary(model_sd_swing_length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = player_xwOBA ~ mean_swing_length + sd_swing_length, \n    data = player_analysis_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.28461 -0.02441  0.00420  0.02957  0.45818 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        0.255807   0.044570   5.739 1.46e-08 ***\nmean_swing_length  0.014405   0.005614   2.566   0.0105 *  \nsd_swing_length   -0.074224   0.011873  -6.252 7.39e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05872 on 644 degrees of freedom\nMultiple R-squared:  0.0837,\tAdjusted R-squared:  0.08085 \nF-statistic: 29.41 on 2 and 644 DF,  p-value: 5.977e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_sd_bat_speed <- lm(player_xwOBA ~ mean_bat_speed + sd_bat_speed, data=player_analysis_df)\nsummary(model_sd_bat_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = player_xwOBA ~ mean_bat_speed + sd_bat_speed, data = player_analysis_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.28346 -0.02297  0.00717  0.02965  0.45133 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -0.1240647  0.0614252  -2.020   0.0438 *  \nmean_bat_speed  0.0060523  0.0008243   7.342 6.36e-13 ***\nsd_bat_speed   -0.0003156  0.0010415  -0.303   0.7620    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05818 on 644 degrees of freedom\nMultiple R-squared:  0.1005,\tAdjusted R-squared:  0.09771 \nF-statistic: 35.98 on 2 and 644 DF,  p-value: 1.544e-15\n```\n\n\n:::\n:::\n\n\n\nIn both models, the Adjusted R-Squared is positive, and the p-value of the coefficient is significant at the 0.05 level. This suggests that there is a significant relationship between player swing consistency and player xwOBA for both swing length and bat speed. The coefficients are negative, suggesting that a more consistent swing length and bat speed is correlated with better offensive production. This likely points to the idea that the best hitters have found optimal swing lengths and bat speeds, and while they will likely slightly deviate from them to better match the pitcher, they have less reason to adjust over the entire season. Worse hitters need to continuously adjust their swings over the season in searching for their best swing type.\n\n#### Multivariate Model\n\nLet's also try one multivariate model to see if we can find a relationship between player swing consistency and xwOBA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_multi <- lm(player_xwOBA ~ mean_swing_length + mean_bat_speed + sd_swing_length + sd_bat_speed,\n                data = player_analysis_df)\nsummary(mod_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = player_xwOBA ~ mean_swing_length + mean_bat_speed + \n    sd_swing_length + sd_bat_speed, data = player_analysis_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.25051 -0.02456  0.00750  0.02774  0.44048 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -0.0560129  0.0607960  -0.921    0.357    \nmean_swing_length -0.0084696  0.0067087  -1.262    0.207    \nmean_bat_speed     0.0066330  0.0009783   6.780 2.73e-11 ***\nsd_swing_length   -0.1243124  0.0187631  -6.625 7.34e-11 ***\nsd_bat_speed       0.0077605  0.0015873   4.889 1.28e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05632 on 642 degrees of freedom\nMultiple R-squared:  0.1599,\tAdjusted R-squared:  0.1546 \nF-statistic: 30.54 on 4 and 642 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(car)\nvif(mod_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean_swing_length    mean_bat_speed   sd_swing_length      sd_bat_speed \n         1.677701          1.928688          2.934572          3.180154 \n```\n\n\n:::\n\n```{.r .cell-code}\n## Show collinearity between predictors\ncor(player_analysis_df$sd_swing_length, player_analysis_df$sd_bat_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8117863\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(player_analysis_df$mean_swing_length, player_analysis_df$mean_bat_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6349418\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(player_analysis_df$mean_swing_length, player_analysis_df$sd_swing_length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2732526\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(player_analysis_df$mean_bat_speed, player_analysis_df$sd_bat_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4694914\n```\n\n\n:::\n:::\n\n\n\nAlthough our VIF values are all less than 5, suggesting that multicollinearity is likely not a problem and just a result of using real imperfect data, we can try to create a \"mechanical variability\" combined component using Principal Components Analysis to combine the two predictors into one.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Standardize variables\nplayer_analysis_df <- player_analysis_df %>%\n  mutate(\n    sd_swing_length_scaled = scale(sd_swing_length),\n    sd_bat_speed_scaled = scale(sd_bat_speed)\n  )\n\n# Step 2: Perform PCA\npca_model <- prcomp(player_analysis_df[, c(\"sd_swing_length_scaled\", \"sd_bat_speed_scaled\")],\n                    center = TRUE, scale. = TRUE)\n\n# Step 3: Add first principal component to the dataset\nplayer_analysis_df <- player_analysis_df %>%\n  mutate(mechanical_variability = pca_model$x[, 1])\n\n# Check PCA results\nsummary(pca_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1     PC2\nStandard deviation     1.3460 0.43384\nProportion of Variance 0.9059 0.09411\nCumulative Proportion  0.9059 1.00000\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(player_xwOBA ~ mean_swing_length + mean_bat_speed + mechanical_variability,\n            data = player_analysis_df)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = player_xwOBA ~ mean_swing_length + mean_bat_speed + \n    mechanical_variability, data = player_analysis_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.28904 -0.02304  0.00739  0.02948  0.44140 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            -0.0595545  0.0567898  -1.049   0.2947    \nmean_swing_length      -0.0086844  0.0068948  -1.260   0.2083    \nmean_bat_speed          0.0059808  0.0009995   5.984 3.62e-09 ***\nmechanical_variability -0.0048351  0.0018997  -2.545   0.0112 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05788 on 643 degrees of freedom\nMultiple R-squared:  0.1112,\tAdjusted R-squared:  0.1071 \nF-statistic: 26.82 on 3 and 643 DF,  p-value: 2.363e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     mean_swing_length         mean_bat_speed mechanical_variability \n              1.677655               1.905632               1.260858 \n```\n\n\n:::\n:::\n\n\n\nOur VIFs are again under 5, signalling that this is a good model.\n\nTakeaway #3: On a player-by-player basis, a player's swing consistency is correlated with better offensive production. This is likely because the best players have found their optimal swing lengths and bat speeds, and while they will slightly deviate from them to better match the pitcher, they have less reason to adjust over the entire season. Worse hitters need to continuously adjust their swings over the season in searching for their best swing type.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}